import Link from "next/link";
import { ChefHat, ShoppingBag, CalendarDays, Boxes, ClipboardCheck, UtensilsCrossed, ArrowRight, AlertTriangle, WalletCards, Clock3, PackageCheck } from "lucide-react";

export function FnbWorkspace({slug,data}:{slug:string;data:any}){
 const actions=[['Menu Management','Manage dishes, pricing, add-ons and availability','/products',UtensilsCrossed],['Orders & POS','Process online and walk-in orders','/orders',ShoppingBag],['Reservations','Manage tables and guest bookings','/bookings',CalendarDays],['Inventory Control','Stock, costs, reconciliation and reorder queue','/inventory',Boxes],['Requisitions','Request supplies before purchasing','/apps/requisition',ClipboardCheck]] as const;
 return <div className="space-y-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-primary">BizNest FnB</p><h1 className="mt-1 text-2xl font-bold tracking-tight">{data.storeName} operations</h1><p className="mt-1 max-w-2xl text-sm text-muted-foreground">One operating center for food, restaurant and grocery businesses. Run service, stock and customer orders from one workspace.</p></div><Link href={`/store/${slug}/admin/apps/requisition`} className="inline-flex items-center justify-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-bold"><ClipboardCheck className="h-4 w-4"/>Request supplies</Link></div>
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric icon={ShoppingBag} label="Today's orders" value={data.orders.length} sub={`₦${data.revenue.toLocaleString()} sales`} /><Metric icon={CalendarDays} label="Reservations" value={data.reservations} sub="Today"/><Metric icon={Boxes} label="Low stock" value={data.lowStock} sub={`${data.outOfStock} out of stock`}/><Metric icon={WalletCards} label="Stock value" value={`₦${data.stockValue.toLocaleString()}`} sub="Known cost basis"/><Metric icon={UtensilsCrossed} label="Catalog items" value={data.menuItems} sub="Physical items"/></div>
 {data.lowStock>0&&<div className="flex items-center gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-amber-800"><AlertTriangle className="h-5 w-5"/><div className="flex-1"><p className="text-sm font-bold">Inventory needs attention</p><p className="mt-0.5 text-xs">{data.lowStock} item{data.lowStock===1?'':'s'} are at or below the current low-stock threshold.</p></div><Link href={`/store/${slug}/admin/inventory`} className="text-xs font-bold underline">Review stock</Link></div>}
 <section className="rounded-2xl border bg-background p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><PackageCheck className="h-4 w-4 text-primary"/><h2 className="text-sm font-bold">FEFO stock rotation</h2></div><p className="mt-1 text-xs text-muted-foreground">Food stock is consumed from the nearest-expiry eligible batch first, with batch cost and expiry tracked.</p></div><Link href={`/store/${slug}/admin/inventory`} className="inline-flex items-center gap-1 text-xs font-bold text-primary">Open inventory <ArrowRight className="h-3.5 w-3.5"/></Link></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Metric icon={Boxes} label="Active batches" value={data.fefo.batchCount} sub={`₦${data.fefo.value.toLocaleString()} FEFO value`} /><Metric icon={Clock3} label="Expiring in 7 days" value={data.fefo.expiringSoon} sub={`${data.fefo.expired} expired batch${data.fefo.expired===1?'':'es'} remaining`} /><Metric icon={PackageCheck} label="FEFO control" value="ON" sub="Nearest expiry consumed first" /></div>{data.fefo.oldest.length>0&&<div className="mt-4 overflow-hidden rounded-xl border"><div className="grid grid-cols-[1fr_auto_auto] gap-3 border-b bg-muted/40 px-4 py-2 text-[10px] font-bold uppercase tracking-wide text-muted-foreground"><span>Oldest available lots</span><span>Remaining</span><span>Received</span></div>{data.fefo.oldest.map((b:any)=><div key={b.id} className="grid grid-cols-[1fr_auto_auto] items-center gap-3 border-b px-4 py-3 text-xs last:border-b-0"><div className="min-w-0"><p className="truncate font-semibold">{b.inventoryItem?.product?.name ?? b.variant?.product?.name ?? "Stock item"}{b.variant?.label?` · ${b.variant.label}`:""}</p><p className="mt-0.5 text-[10px] text-muted-foreground">Batch {b.batchNumber || "—"}{b.expiryDate?` · Expires ${new Date(b.expiryDate).toLocaleDateString()}`:""}</p></div><span className="font-bold">{b.quantityRemaining}</span><span className="text-muted-foreground">{new Date(b.receivedAt).toLocaleDateString()}</span></div>)}</div>}</section>
 <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{actions.map(([title,desc,href,Icon])=><Link key={title} href={`/store/${slug}/admin${href}`} className="group rounded-2xl border bg-background p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-primary/40 hover:shadow-md"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="h-5 w-5"/></span><h2 className="mt-4 text-sm font-bold">{title}</h2><p className="mt-1 min-h-10 text-xs leading-5 text-muted-foreground">{desc}</p><span className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-primary">Open <ArrowRight className="h-3.5 w-3.5 transition group-hover:translate-x-0.5"/></span></Link>)}</div>
 <section className="overflow-hidden rounded-2xl border bg-background shadow-sm"><div className="border-b px-5 py-4"><h2 className="text-sm font-bold">Today's activity</h2><p className="mt-1 text-xs text-muted-foreground">Latest orders across online and POS channels.</p></div><div className="divide-y">{data.orders.map((o:any)=><div key={o.id} className="flex items-center gap-4 px-5 py-4"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-muted"><ShoppingBag className="h-4 w-4"/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{o.posCustomerName||`Order ${o.id.slice(-6).toUpperCase()}`}</p><p className="mt-0.5 text-[11px] text-muted-foreground">{o.channel} · {o.items.reduce((s:any,i:any)=>s+i.quantity,0)} item(s) · {o.status.replace('_',' ')}</p></div><p className="text-sm font-bold">{o.currency} {Number(o.total).toLocaleString()}</p></div>)}{data.orders.length===0&&<div className="px-5 py-10 text-center text-xs text-muted-foreground">No orders recorded today.</div>}</div></section>
 </div>
}
function Metric({icon:Icon,label,value,sub}:{icon:any;label:string;value:any;sub:string}){return <div className="rounded-2xl border bg-background p-4 shadow-sm"><div className="flex items-center justify-between"><span className="text-[11px] font-medium text-muted-foreground">{label}</span><Icon className="h-4 w-4 text-primary"/></div><p className="mt-2 text-xl font-bold tracking-tight">{value}</p><p className="mt-1 text-[10px] text-muted-foreground">{sub}</p></div>}
