"use client";

import { useState, useTransition } from "react";
import { Plus, Trash2, Save, Image as ImageIcon, CalendarDays, Tag, Sparkles, Home, Utensils, Compass, Info, Mail } from "lucide-react";
import { saveHotelSection } from "@/lib/actions/hotel-content";
import { SingleImageUpload } from "@/components/forms/single-image-upload";
import { HOTEL_GALLERY_CATEGORIES, HOTEL_OFFER_CATEGORIES, HOTEL_AMENITY_CATEGORIES, type HotelContent, type HotelOffer, type HotelGalleryItem, type HotelEvent, type HotelAmenity, type HotelPageContent } from "@/lib/hotel-content";

type Tab="home"|"dining"|"facilities"|"experiences"|"about"|"contact"|"gallery"|"amenities"|"events"|"offers";
const blankPage:HotelPageContent={eyebrow:"",title:"",subtitle:"",image:"",body:"",ctaLabel:"",ctaHref:"",cards:[],features:[],stats:[]};

export function HotelContentManager({slug,initial}:{slug:string;initial:HotelContent}){
 const [tab,setTab]=useState<Tab>("home");
 const [pages,setPages]=useState({home:initial.home,dining:initial.dining,experiences:initial.experiences,about:initial.about,contact:initial.contact});
 const [gallery,setGallery]=useState(initial.gallery);const [amenities,setAmenities]=useState(initial.amenities);const [events,setEvents]=useState(initial.events);const [offers,setOffers]=useState(initial.offers);const [busy,start]=useTransition();const [msg,setMsg]=useState("");
 const save=()=>start(async()=>{setMsg("");let section=tab==="facilities"?"hotel-amenities":"hotel-"+tab;let content:any;if(["home","dining","experiences","about","contact"].includes(tab))content={page:pages[tab as keyof typeof pages]};else if(tab==="gallery")content={items:gallery};else if(tab==="amenities"||tab==="facilities")content={amenities};else if(tab==="events")content={events};else content={offers};const r=await saveHotelSection(slug,section,content);setMsg(r.success?"Published successfully.":r.error||"Could not save.")});
 const tabs:[Tab,string,React.ReactNode][]=[["home","Homepage",<Home key="1"/>],["dining","Dining",<Utensils key="2"/>],["facilities","Facilities",<Sparkles key="3"/>],["experiences","Experiences",<Compass key="4"/>],["about","About",<Info key="5"/>],["contact","Contact",<Mail key="6"/>],["gallery","Gallery",<ImageIcon key="7"/>],["events","Events",<CalendarDays key="9"/>],["offers","Offers",<Tag key="10"/>]];
 return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Hotel Website Content</h1><p className="text-sm text-muted-foreground">Edit every customer-facing section of the Veloura/Lusso hotel experience. Rooms remain managed through <a className="underline" href={`/store/${slug}/admin/services`}>Services / Rooms</a>.</p></div><button onClick={save} disabled={busy} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground"><Save className="h-4 w-4"/>{busy?"Publishing…":"Publish Changes"}</button></div>{msg&&<p className="rounded-lg border bg-muted/40 p-3 text-sm">{msg}</p>}<div className="flex flex-wrap gap-1 border-b">{tabs.map(([key,label,icon])=><button key={key} onClick={()=>setTab(key)} className={`inline-flex items-center gap-1 px-3 py-3 text-xs font-semibold ${tab===key?"border-b-2 border-primary":"text-muted-foreground"}`}>{icon}{label}</button>)}</div>
 {["home","dining","experiences","about","contact"].includes(tab)&&<PageEditor page={pages[tab as keyof typeof pages]||blankPage} onChange={p=>setPages(x=>({...x,[tab]:p}))}/>} 
 {tab==="gallery"&&<GalleryEditor items={gallery} setItems={setGallery}/>} {(tab==="amenities"||tab==="facilities")&&<AmenityEditor items={amenities} setItems={setAmenities}/>} {tab==="events"&&<EventEditor items={events} setItems={setEvents}/>} {tab==="offers"&&<OfferEditor items={offers} setItems={setOffers}/>} </div>
}

function PageEditor({page,onChange}:{page:HotelPageContent;onChange:(p:HotelPageContent)=>void}){const patch=(v:Partial<HotelPageContent>)=>onChange({...page,...v});return <section className="space-y-5"><div className="grid gap-4 md:grid-cols-[220px_1fr]"><SingleImageUpload value={page.image} onChange={image=>patch({image})} label="Hero / feature image"/><div className="grid gap-3 md:grid-cols-2"><Field label="Eyebrow"><input value={page.eyebrow} onChange={e=>patch({eyebrow:e.target.value})}/></Field><Field label="Title"><input value={page.title} onChange={e=>patch({title:e.target.value})}/></Field><Field label="Subtitle"><textarea value={page.subtitle} onChange={e=>patch({subtitle:e.target.value})}/></Field><Field label="Body / intro"><textarea value={page.body||""} onChange={e=>patch({body:e.target.value})}/></Field><Field label="CTA label"><input value={page.ctaLabel||""} onChange={e=>patch({ctaLabel:e.target.value})}/></Field><Field label="CTA link"><input value={page.ctaHref||""} onChange={e=>patch({ctaHref:e.target.value})}/></Field></div></div><div className="grid gap-4 md:grid-cols-3"><ListEditor title="Stats" items={page.stats||[]} onChange={stats=>patch({stats})} fields={[["value","Value"],["label","Label"]]}/><ListEditor title="Features" items={page.features||[]} onChange={features=>patch({features})} fields={[["title","Title"],["description","Description"]]}/><CardEditor cards={page.cards||[]} onChange={cards=>patch({cards})}/></div></section>}

function CardEditor({cards,onChange}:{cards:NonNullable<HotelPageContent["cards"]>;onChange:(v:NonNullable<HotelPageContent["cards"]>)=>void}){return <div className="rounded-2xl border p-4"><div className="mb-3 flex items-center justify-between"><b>Cards</b><button className="rounded-lg border px-2 py-1 text-xs" onClick={()=>onChange([...cards,{id:crypto.randomUUID(),title:"New Card",description:"",image:""}])}><Plus className="mr-1 inline h-3 w-3"/>Add</button></div><div className="space-y-3">{cards.map((c,i)=><div key={c.id} className="rounded-xl border p-3"><SingleImageUpload value={c.image} onChange={image=>onChange(cards.map((x,j)=>j===i?{...x,image}:x))} label="Card image"/><div className="grid gap-2 mt-2"><input value={c.eyebrow||""} placeholder="Eyebrow" onChange={e=>onChange(cards.map((x,j)=>j===i?{...x,eyebrow:e.target.value}:x))}/><input value={c.title} placeholder="Title" onChange={e=>onChange(cards.map((x,j)=>j===i?{...x,title:e.target.value}:x))}/><textarea value={c.description} placeholder="Description" onChange={e=>onChange(cards.map((x,j)=>j===i?{...x,description:e.target.value}:x))}/><input value={c.meta||""} placeholder="Meta / hours" onChange={e=>onChange(cards.map((x,j)=>j===i?{...x,meta:e.target.value}:x))}/></div><button className="mt-2 text-xs text-destructive" onClick={()=>onChange(cards.filter(x=>x.id!==c.id))}><Trash2 className="mr-1 inline h-3 w-3"/>Remove</button></div>)}</div></div>}

function ListEditor({title,items,onChange,fields}:{title:string;items:any[];onChange:(v:any[])=>void;fields:[string,string][]}){return <div className="rounded-2xl border p-4"><div className="mb-3 flex items-center justify-between"><b>{title}</b><button className="rounded-lg border px-2 py-1 text-xs" onClick={()=>onChange([...items,{id:crypto.randomUUID(),[fields[0][0]]:"",[fields[1][0]]:""}])}><Plus className="mr-1 inline h-3 w-3"/>Add</button></div><div className="space-y-2">{items.map((item,i)=><div key={item.id} className="rounded-xl border p-3 grid gap-2">{fields.map(([key,label])=><input key={key} placeholder={label} value={item[key]||""} onChange={e=>onChange(items.map((x,j)=>j===i?{...x,[key]:e.target.value}:x))}/>) }<button className="text-xs text-destructive text-left" onClick={()=>onChange(items.filter(x=>x.id!==item.id))}><Trash2 className="mr-1 inline h-3 w-3"/>Remove</button></div>)}</div></div>}

function GalleryEditor({items,setItems}:{items:HotelGalleryItem[];setItems:(v:HotelGalleryItem[])=>void}){return <section className="space-y-4"><AddButton label="Add Photo" onClick={()=>setItems([...items,{id:crypto.randomUUID(),title:"New Photo",category:"Hotel Interior",image:"",description:""}])}/>{items.map((g,i)=><article key={g.id} className="rounded-2xl border p-5"><div className="grid gap-3 md:grid-cols-[176px_1fr]"><SingleImageUpload value={g.image} onChange={image=>setItems(items.map((x,j)=>j===i?{...x,image}:x))} label="Upload photo"/><div className="grid gap-3 md:grid-cols-2"><Field label="Title"><input value={g.title} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,title:e.target.value}:x))}/></Field><Field label="Category"><select value={g.category} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,category:e.target.value}:x))}>{HOTEL_GALLERY_CATEGORIES.filter(x=>x!=="All").map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Description"><textarea value={g.description||""} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,description:e.target.value}:x))}/></Field></div></div><Remove onClick={()=>setItems(items.filter(x=>x.id!==g.id))}/></article>)}</section>}
function AmenityEditor({items,setItems}:{items:HotelAmenity[];setItems:(v:HotelAmenity[])=>void}){return <section className="space-y-4"><AddButton label="Add Facility" onClick={()=>setItems([...items,{id:crypto.randomUUID(),title:"New Facility",category:"Guest Services",description:"",image:"",icon:"sparkles"}])}/>{items.map((a,i)=><article key={a.id} className="rounded-2xl border p-5"><div className="grid gap-3 md:grid-cols-[176px_1fr]"><SingleImageUpload value={a.image} onChange={image=>setItems(items.map((x,j)=>j===i?{...x,image}:x))} label="Facility photo"/><div className="grid gap-3 md:grid-cols-2"><Field label="Title"><input value={a.title} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,title:e.target.value}:x))}/></Field><Field label="Category"><select value={a.category} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,category:e.target.value}:x))}>{HOTEL_AMENITY_CATEGORIES.filter(x=>x!=="All Amenities").map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Description"><textarea value={a.description} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,description:e.target.value}:x))}/></Field></div></div><Remove onClick={()=>setItems(items.filter(x=>x.id!==a.id))}/></article>)}</section>}
function EventEditor({items,setItems}:{items:HotelEvent[];setItems:(v:HotelEvent[])=>void}){return <section className="space-y-4"><AddButton label="Add Event" onClick={()=>setItems([...items,{id:crypto.randomUUID(),slug:`event-${items.length+1}`,title:"New Event",category:"Entertainment",date:"",time:"",venue:"",description:"",details:"",image:""}])}/>{items.map((ev,i)=><article key={ev.id} className="rounded-2xl border p-5"><div className="grid gap-3 md:grid-cols-[176px_1fr]"><SingleImageUpload value={ev.image} onChange={image=>setItems(items.map((x,j)=>j===i?{...x,image}:x))} label="Event photo"/><div className="grid gap-3 md:grid-cols-2"><Field label="Title"><input value={ev.title} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,title:e.target.value}:x))}/></Field><Field label="Category"><input value={ev.category} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,category:e.target.value}:x))}/></Field><Field label="Date"><input type="date" value={ev.date} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,date:e.target.value}:x))}/></Field><Field label="Time"><input value={ev.time} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,time:e.target.value}:x))}/></Field><Field label="Venue"><input value={ev.venue} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,venue:e.target.value}:x))}/></Field><Field label="Description"><textarea value={ev.description} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,description:e.target.value}:x))}/></Field><Field label="Details"><textarea value={ev.details} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,details:e.target.value}:x))}/></Field></div></div><Remove onClick={()=>setItems(items.filter(x=>x.id!==ev.id))}/></article>)}</section>}
function OfferEditor({items,setItems}:{items:HotelOffer[];setItems:(v:HotelOffer[])=>void}){return <section className="space-y-4"><AddButton label="Add Offer" onClick={()=>setItems([...items,{id:crypto.randomUUID(),title:"New Offer",category:"Room Packages",description:"",price:0,image:"",badge:"",benefits:[]}])}/>{items.map((o,i)=><article key={o.id} className="rounded-2xl border p-5"><div className="grid gap-3 md:grid-cols-[176px_1fr]"><SingleImageUpload value={o.image} onChange={image=>setItems(items.map((x,j)=>j===i?{...x,image}:x))} label="Offer photo"/><div className="grid gap-3 md:grid-cols-2"><Field label="Title"><input value={o.title} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,title:e.target.value}:x))}/></Field><Field label="Category"><select value={o.category} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,category:e.target.value}:x))}>{HOTEL_OFFER_CATEGORIES.filter(x=>x!=="All Offers").map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Badge"><input value={o.badge} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,badge:e.target.value}:x))}/></Field><Field label="Price"><input type="number" value={o.price} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,price:Number(e.target.value)}:x))}/></Field><Field label="Description"><textarea value={o.description} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,description:e.target.value}:x))}/></Field><Field label="Benefits, one per line"><textarea value={o.benefits.join("\n")} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,benefits:e.target.value.split("\n").filter(Boolean)}:x))}/></Field></div></div><Remove onClick={()=>setItems(items.filter(x=>x.id!==o.id))}/></article>)}</section>}
function AddButton({label,onClick}:{label:string;onClick:()=>void}){return <div className="flex justify-end"><button onClick={onClick} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold"><Plus className="h-4 w-4"/>{label}</button></div>}
function Remove({onClick}:{onClick:()=>void}){return <div className="mt-3 flex justify-end"><button onClick={onClick} className="inline-flex items-center gap-1 text-sm text-destructive"><Trash2 className="h-4 w-4"/>Remove</button></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="space-y-1 text-sm"><span className="font-medium">{label}</span><div className="[&_input]:w-full [&_input]:rounded-lg [&_input]:border [&_input]:bg-background [&_input]:px-3 [&_input]:py-2 [&_select]:w-full [&_select]:rounded-lg [&_select]:border [&_select]:bg-background [&_select]:px-3 [&_select]:py-2 [&_textarea]:min-h-20 [&_textarea]:w-full [&_textarea]:rounded-lg [&_textarea]:border [&_textarea]:bg-background [&_textarea]:px-3 [&_textarea]:py-2">{children}</div></label>}
