"use client";
import { useState, useTransition, type FormEvent } from "react";
import { BriefcaseBusiness, CalendarDays, CheckCircle2, Clock3, Plus, Users, Wallet, X } from "lucide-react";
import { createHrEmployee, createHrPayrollRun, recordHrAttendance, requestHrLeave, decideHrLeave } from "@/lib/actions/hr-payroll";

type Data = Awaited<ReturnType<typeof import("@/lib/actions/hr-payroll").getHrDashboard>>;
const fmt=(n:number)=>`₦${n.toLocaleString("en-NG",{maximumFractionDigits:0})}`;
function Metric({icon:Icon,label,value,sub}:{icon:any;label:string;value:string|number;sub:string}){return <div className="rounded-xl border bg-background p-3"><div className="flex items-center justify-between"><span className="text-[11px] text-muted-foreground">{label}</span><Icon className="h-4 w-4 text-primary"/></div><p className="mt-1.5 text-xl font-bold">{value}</p><p className="mt-1 text-[10px] text-muted-foreground">{sub}</p></div>}
export function HrPayrollWorkspace({slug,data}:{slug:string;data:Exclude<Data,{error:string}>}){
 const [d,setD]=useState(data); const [tab,setTab]=useState<"overview"|"employees"|"attendance"|"leave"|"payroll">("overview"); const [show,setShow]=useState(false); const [payroll,setPayroll]=useState(false); const [pending,start]=useTransition(); const [msg,setMsg]=useState("");
 const refresh=async()=>{const r=await fetch(`/store/${slug}/admin/apps/hr-payroll/data`,{cache:"no-store"}).then(x=>x.json()); if(r&& !r.error)setD(r)};
 const submitEmployee=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();start(async()=>{const r=await createHrEmployee(slug,new FormData(e.currentTarget));if(!r.success)setMsg(r.error||"Could not create employee");else{setShow(false);e.currentTarget.reset();await refresh()}})};
 const runPayroll=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();start(async()=>{const f=new FormData(e.currentTarget);const r=await createHrPayrollRun(slug,String(f.get("start")),String(f.get("end")));if(!r.success)setMsg(r.error||"Could not run payroll");else{setPayroll(false);await refresh()}})};
 return <div className="space-y-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-primary">BizNest People Operations</p><h1 className="mt-1 text-2xl font-bold tracking-tight">HR & Payroll</h1><p className="mt-1 text-sm text-muted-foreground">Manage employees, attendance, leave and payroll from one operational workspace.</p></div><div className="flex gap-2"><button onClick={()=>setShow(true)} className="inline-flex items-center gap-2 rounded-lg bg-primary px-3 py-2 text-xs font-bold text-primary-foreground"><Plus className="h-3.5 w-3.5"/>Employee</button><button onClick={()=>setPayroll(true)} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-bold"><Wallet className="h-3.5 w-3.5"/>Run payroll</button></div></div>
 {msg&&<div className="flex items-center justify-between rounded-lg border border-rose-200 bg-rose-50 p-2.5 text-xs text-rose-700"><span>{msg}</span><button onClick={()=>setMsg("")}><X className="h-3.5 w-3.5"/></button></div>}
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Users} label="Employees" value={d.employees} sub="Active workforce"/><Metric icon={CheckCircle2} label="Present today" value={d.present} sub="Attendance recorded"/><Metric icon={CalendarDays} label="Leave requests" value={d.pendingLeave} sub="Awaiting approval"/><Metric icon={Wallet} label="Latest net payroll" value={d.latestRun?fmt(d.latestRun.totalNet):"—"} sub={d.latestRun?d.latestRun.status:"No payroll run"}/></div>
 <div className="flex gap-1 overflow-x-auto border-b">{(["overview","employees","attendance","leave","payroll"] as const).map(x=><button key={x} onClick={()=>setTab(x)} className={`whitespace-nowrap px-3 py-2 text-xs font-semibold ${tab===x?"border-b-2 border-primary text-primary":"text-muted-foreground"}`}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div>
 {tab==="overview"&&<div className="grid gap-3 lg:grid-cols-2"><section className="rounded-xl border p-4"><h2 className="text-sm font-bold">Today's attendance</h2><div className="mt-3 space-y-2">{d.attendance.slice(0,8).map(a=><div key={a.id} className="flex items-center gap-3 rounded-lg border p-2.5 text-xs"><span className="font-semibold">{a.employee.firstName} {a.employee.lastName}</span><span className="ml-auto rounded-full bg-muted px-2 py-1 text-[10px] font-bold">{a.status}</span></div>)}{!d.attendance.length&&<p className="text-xs text-muted-foreground">No attendance has been recorded today.</p>}</div></section><section className="rounded-xl border p-4"><h2 className="text-sm font-bold">Latest payroll</h2>{d.latestRun?<div className="mt-3 grid grid-cols-3 gap-2 text-xs"><div><span className="text-muted-foreground">Gross</span><p className="mt-1 font-bold">{fmt(d.latestRun.totalGross)}</p></div><div><span className="text-muted-foreground">Deductions</span><p className="mt-1 font-bold">{fmt(d.latestRun.totalDeductions)}</p></div><div><span className="text-muted-foreground">Net</span><p className="mt-1 font-bold">{fmt(d.latestRun.totalNet)}</p></div></div>:<p className="mt-3 text-xs text-muted-foreground">No payroll run yet.</p>}</section></div>}
 {tab==="attendance"&&<section className="rounded-xl border p-4"><h2 className="text-sm font-bold">Attendance control</h2><div className="mt-3 space-y-2">{d.attendance.map(a=><div key={a.id} className="flex flex-wrap items-center gap-2 rounded-lg border p-2.5 text-xs"><span className="font-semibold">{a.employee.firstName} {a.employee.lastName}</span><span className="ml-auto text-muted-foreground">{a.status}</span>{["PRESENT","LATE","ABSENT","HALF_DAY"].map(s=><button key={s} disabled={pending} onClick={()=>start(async()=>{await recordHrAttendance(slug,a.employee.id,s);await refresh()})} className="rounded border px-2 py-1 text-[10px] font-semibold">{s}</button>)}</div>)}{!d.attendance.length&&<p className="text-xs text-muted-foreground">Create employee attendance records from the employee roster.</p>}</div></section>}
 {tab==="employees"&&<section className="rounded-xl border p-4"><div className="flex items-center justify-between gap-3"><div><div className="flex items-center gap-2"><BriefcaseBusiness className="h-4 w-4 text-primary"/><h2 className="text-sm font-bold">Employee management</h2></div><p className="mt-1 text-xs text-muted-foreground">Employee records are the HR source of truth; compensation and employment status stay here.</p></div><button onClick={()=>setShow(true)} className="shrink-0 rounded-lg bg-primary px-3 py-2 text-xs font-bold text-primary-foreground">Add employee</button></div><div className="mt-4 rounded-lg border border-dashed p-5 text-center text-xs text-muted-foreground">Your employee directory will appear here after employees are added.</div></section>}
 {tab==="leave"&&<section className="rounded-xl border p-4"><h2 className="text-sm font-bold">Leave management</h2><p className="mt-2 text-xs text-muted-foreground">Review requests, prevent overlapping leave and approve or reject time away.</p><div className="mt-3 rounded-lg border border-dashed p-5 text-center text-xs text-muted-foreground">Leave requests will appear here as employees submit them.</div></section>}
 {tab==="payroll"&&<section className="rounded-xl border p-4"><h2 className="text-sm font-bold">Payroll runs</h2><p className="mt-2 text-xs text-muted-foreground">Generate a controlled payroll run from employee compensation records and review gross, deductions and net totals.</p><button onClick={()=>setPayroll(true)} className="mt-3 rounded-lg bg-primary px-3 py-2 text-xs font-bold text-primary-foreground">Create payroll run</button></section>}
 {show&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-3"><div className="w-full max-w-lg max-h-[90vh] overflow-y-auto rounded-xl border bg-background p-5 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-base font-bold">Add employee</h2><button onClick={()=>setShow(false)}><X className="h-4 w-4"/></button></div><form onSubmit={submitEmployee} className="mt-4 grid gap-2.5"><div className="grid gap-2 sm:grid-cols-2"><input required name="firstName" placeholder="First name" className="rounded-lg border px-3 py-2 text-sm"/><input required name="lastName" placeholder="Last name" className="rounded-lg border px-3 py-2 text-sm"/></div><div className="grid gap-2 sm:grid-cols-2"><input required name="employeeNo" placeholder="Employee number" className="rounded-lg border px-3 py-2 text-sm"/><input name="position" placeholder="Position" className="rounded-lg border px-3 py-2 text-sm"/></div><div className="grid gap-2 sm:grid-cols-2"><input name="department" placeholder="Department" className="rounded-lg border px-3 py-2 text-sm"/><input name="email" type="email" placeholder="Email" className="rounded-lg border px-3 py-2 text-sm"/></div><input name="hireDate" type="date" className="rounded-lg border px-3 py-2 text-sm"/><div className="grid gap-2 sm:grid-cols-2"><input name="basicSalary" type="number" min="0" placeholder="Basic salary" className="rounded-lg border px-3 py-2 text-sm"/><input name="housingAllowance" type="number" min="0" placeholder="Housing allowance" className="rounded-lg border px-3 py-2 text-sm"/><input name="transportAllowance" type="number" min="0" placeholder="Transport allowance" className="rounded-lg border px-3 py-2 text-sm"/><input name="otherAllowance" type="number" min="0" placeholder="Other allowance" className="rounded-lg border px-3 py-2 text-sm"/></div><button disabled={pending} className="mt-1 rounded-lg bg-primary py-2.5 text-xs font-bold text-primary-foreground">{pending?"Saving…":"Create employee"}</button></form></div></div>}
 {payroll&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-3"><div className="w-full max-w-md rounded-xl border bg-background p-5 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-base font-bold">Run payroll</h2><button onClick={()=>setPayroll(false)}><X className="h-4 w-4"/></button></div><form onSubmit={runPayroll} className="mt-4 grid gap-3"><input required name="start" type="date" className="rounded-lg border px-3 py-2 text-sm"/><input required name="end" type="date" className="rounded-lg border px-3 py-2 text-sm"/><button disabled={pending} className="rounded-lg bg-primary py-2.5 text-xs font-bold text-primary-foreground">{pending?"Generating…":"Generate payroll"}</button></form></div></div>}</div>;
}
