"use client";

import { useState, useTransition, type FormEvent } from "react";
import { ClipboardCheck, Plus, Clock3, CircleCheck, AlertTriangle, X, Send } from "lucide-react";
import { createRequisition, submitRequisition, type RequisitionLineInput } from "@/lib/actions/requisition";

type Row = { id:string; number:string; title:string; department:string|null; requesterName:string|null; priority:string; status:string; neededBy:Date|null; createdAt:Date; items:{id:string;description:string;quantity:number;unit:string|null;estimatedUnitCost:any}[] };
type Summary = { total:number; pending:number; approved:number; urgent:number };
const statusTone:Record<string,string>={DRAFT:"bg-muted text-muted-foreground",SUBMITTED:"bg-amber-100 text-amber-700",APPROVED:"bg-emerald-100 text-emerald-700",REJECTED:"bg-rose-100 text-rose-700",CONVERTED:"bg-blue-100 text-blue-700",CANCELLED:"bg-muted text-muted-foreground"};
const priorityTone:Record<string,string>={LOW:"text-muted-foreground",NORMAL:"text-foreground",HIGH:"text-amber-700",URGENT:"text-rose-700"};

export function RequisitionWorkspace({slug,rows,summary}:{slug:string;rows:Row[];summary:Summary}){
 const [show,setShow]=useState(false); const [pending,start]=useTransition(); const [msg,setMsg]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const items:RequisitionLineInput[]=[{description:String(fd.get("item")||""),quantity:Number(fd.get("quantity")||0),unit:String(fd.get("unit")||"")||undefined,estimatedUnitCost:Number(fd.get("cost")||0)||undefined}];start(async()=>{const r=await createRequisition(slug,{title:String(fd.get("title")||""),department:String(fd.get("department")||"")||undefined,requesterName:String(fd.get("requester")||"")||undefined,priority:String(fd.get("priority")||"NORMAL"),neededBy:String(fd.get("neededBy")||"")||undefined,notes:String(fd.get("notes")||"")||undefined,items});if(r.success){setShow(false);location.reload()}else setMsg(r.error)})}
 function action(fn:()=>Promise<any>){start(async()=>{const r=await fn();if(r.success)location.reload();else setMsg(r.error)})}
 return <div className="space-y-5">
  <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-primary">BizNest Operations</p><h1 className="mt-1 text-2xl font-bold tracking-tight">Requisitions</h1><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Control internal purchasing requests before money leaves the business. Every request has an owner, priority, approval state and audit trail.</p></div><button onClick={()=>{setMsg("");setShow(true)}} className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground"><Plus className="h-4 w-4"/>New requisition</button></div>
  {msg&&<div className="flex items-center justify-between rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700"><span>{msg}</span><button onClick={()=>setMsg("")}><X className="h-4 w-4"/></button></div>}
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={ClipboardCheck} label="Total requests" value={summary.total} sub="Open history"/><Metric icon={Clock3} label="Awaiting approval" value={summary.pending} sub="Needs a decision"/><Metric icon={CircleCheck} label="Approved" value={summary.approved} sub="Ready for purchasing"/><Metric icon={AlertTriangle} label="Urgent" value={summary.urgent} sub="Needs attention"/></div>
  <section className="overflow-hidden rounded-2xl border bg-background shadow-sm"><div className="border-b px-5 py-4"><h2 className="text-sm font-bold">Request queue</h2><p className="mt-1 text-xs text-muted-foreground">Keep requests separate from purchase orders until they are approved.</p></div><div className="divide-y">{rows.map(r=><div key={r.id} className="grid gap-4 p-5 lg:grid-cols-[1.5fr_.8fr_.7fr_.7fr_auto] lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className="font-semibold">{r.title}</span><span className="text-[10px] font-bold text-muted-foreground">{r.number}</span></div><p className="mt-1 text-xs text-muted-foreground">{r.department||"General"} · {r.requesterName||"Unassigned requester"} · {r.items.length} line{r.items.length===1?"":"s"}</p></div><div className={`text-xs font-bold ${priorityTone[r.priority]}`}>{r.priority}</div><div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${statusTone[r.status]||"bg-muted"}`}>{r.status.replace("_"," ")}</span></div><div className="text-xs text-muted-foreground">{r.neededBy?`Need by ${new Date(r.neededBy).toLocaleDateString("en-NG")}`:`Created ${new Date(r.createdAt).toLocaleDateString("en-NG")}`}</div><div className="flex flex-wrap justify-end gap-2">{r.status==="DRAFT"&&<button disabled={pending} onClick={()=>action(()=>submitRequisition(slug,r.id))} className="inline-flex items-center gap-1.5 rounded-lg border px-3 py-2 text-xs font-bold"><Send className="h-3 w-3"/>Submit</button>}{r.status==="SUBMITTED"&&<span className="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-[11px] font-bold text-amber-700">Awaiting Financial Control</span>}</div></div>)}{rows.length===0&&<div className="px-6 py-14 text-center"><ClipboardCheck className="mx-auto h-8 w-8 text-muted-foreground"/><p className="mt-3 text-sm font-semibold">No requisitions yet</p><p className="mt-1 text-xs text-muted-foreground">Create your first internal request to start the approval trail.</p></div>}</div></section>
  {show&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-3 sm:p-4"><div className="flex max-h-[calc(100vh-1.5rem)] w-full max-w-lg flex-col overflow-hidden rounded-2xl border bg-background shadow-xl sm:max-h-[calc(100vh-2rem)]"><div className="flex shrink-0 items-start justify-between border-b px-5 py-4"><div><h2 className="text-lg font-bold">New requisition</h2><p className="mt-1 text-xs text-muted-foreground">Request stock, supplies, equipment or a service.</p></div><button onClick={()=>setShow(false)}><X/></button></div><form onSubmit={submit} className="min-h-0 overflow-y-auto px-5 py-4 grid gap-2.5"><Input name="title" label="Request title" placeholder="Weekly kitchen supplies"/><div className="grid gap-3 sm:grid-cols-2"><Input name="department" label="Department" placeholder="Kitchen / Operations"/><Input name="requester" label="Requested by" placeholder="Staff member"/></div><div className="grid gap-3 sm:grid-cols-3"><Select name="priority" label="Priority" options={["LOW","NORMAL","HIGH","URGENT"]}/><Input name="neededBy" label="Needed by" type="date"/><Input name="item" label="First item" placeholder="Cooking oil"/></div><div className="grid gap-3 sm:grid-cols-2"><Input name="quantity" label="Quantity" type="number" min="1" defaultValue="1"/><Input name="unit" label="Unit" placeholder="bottle / carton / pack"/></div><Input name="cost" label="Estimated unit cost (₦)" type="number" min="0"/><label className="grid gap-1.5 text-xs font-medium">Notes<textarea name="notes" rows={3} className="rounded-lg border bg-background p-2.5 text-sm" placeholder="Reason, specification or preferred supplier..."/></label><div className="sticky bottom-0 -mx-5 mt-1 border-t bg-background px-5 pt-3 pb-1"><button type="submit" disabled={pending} className="w-full rounded-lg bg-primary py-2.5 text-sm font-bold text-primary-foreground">{pending?"Creating…":"Create requisition"}</button></div></form></div></div>}
 </div>
}
function Metric({icon:Icon,label,value,sub}:{icon:any;label:string;value:number;sub:string}){return <div className="rounded-2xl border bg-background p-5 shadow-sm"><div className="flex items-center justify-between"><span className="text-xs font-medium text-muted-foreground">{label}</span><Icon className="h-4 w-4 text-primary"/></div><p className="mt-2 text-2xl font-bold">{value}</p><p className="mt-1 text-[11px] text-muted-foreground">{sub}</p></div>}
function Input({name,label,placeholder,type="text",defaultValue,min}:{name:string;label:string;placeholder?:string;type?:string;defaultValue?:string;min?:string}){return <label className="grid gap-1.5 text-xs font-medium">{label}<input required={name!=="department"&&name!=="requester"&&name!=="unit"&&name!=="cost"&&name!=="neededBy"} name={name} type={type} min={min} defaultValue={defaultValue} placeholder={placeholder} className="rounded-lg border bg-background px-3 py-2 text-sm font-normal"/></label>}
function Select({name,label,options}:{name:string;label:string;options:string[]}){return <label className="grid gap-1.5 text-xs font-medium">{label}<select name={name} className="rounded-lg border bg-background px-3 py-2 text-sm font-normal">{options.map(o=><option key={o}>{o}</option>)}</select></label>}
