"use client";

import { useState, useTransition, type ReactNode } from "react";
import { CheckCircle2, Globe2, Image, Info, Link2, MapPin, Search, ShieldCheck, Sparkles } from "lucide-react";
import { saveStoreSeo } from "@/lib/actions/seo-crm";

export function SeoWorkspace({slug,initial}:{slug:string;initial:{name:string;seoTitle:string;seoDescription:string;seoKeywords:string;seoCanonicalUrl:string;seoOgImage:string;seoNoIndex:boolean;seoGoogleVerification:string}}){
 const [v,setV]=useState(initial); const [pending,start]=useTransition(); const [msg,setMsg]=useState("");
 const save=()=>start(async()=>{const r=await saveStoreSeo(slug,{title:v.seoTitle,description:v.seoDescription,keywords:v.seoKeywords,canonicalUrl:v.seoCanonicalUrl,ogImage:v.seoOgImage,noIndex:v.seoNoIndex,googleVerification:v.seoGoogleVerification});setMsg(r.success?"SEO settings saved successfully.":r.error||"Could not save SEO settings.")});
 const origin=typeof window!=="undefined"?window.location.origin:"https://biznest.space";
 const url=v.seoCanonicalUrl||`${origin}/${slug}`;
 return <div className="space-y-6">
  <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]">
   <section className="rounded-3xl border bg-background p-6 shadow-sm"><div className="mb-6 flex items-start justify-between"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-primary"><Sparkles className="h-3.5 w-3.5"/>BizNest App</div><h2 className="mt-1 text-xl font-bold">Search visibility</h2><p className="mt-1 text-sm text-muted-foreground">Control how this website appears in Google and other search engines.</p></div><Search className="h-5 w-5 text-primary"/></div>
    <div className="grid gap-5"><Field label="SEO title" hint={`${v.seoTitle.length}/180`}><input value={v.seoTitle} onChange={e=>setV({...v,seoTitle:e.target.value})} className="field"/></Field><Field label="Meta description" hint={`${v.seoDescription.length}/320`}><textarea rows={4} value={v.seoDescription} onChange={e=>setV({...v,seoDescription:e.target.value})} className="field resize-none"/></Field><Field label="Keywords" hint="Optional"><input value={v.seoKeywords} onChange={e=>setV({...v,seoKeywords:e.target.value})} placeholder="hotel Abuja, luxury rooms, accommodation" className="field"/></Field><Field label="Canonical URL" hint="Optional"><div className="relative"><Link2 className="absolute left-3 top-3.5 h-4 w-4 text-muted-foreground"/><input value={v.seoCanonicalUrl} onChange={e=>setV({...v,seoCanonicalUrl:e.target.value})} placeholder="https://yourdomain.com/" className="field pl-9"/></div></Field><Field label="Social share image" hint="Recommended 1200 × 630"><div className="relative"><Image className="absolute left-3 top-3.5 h-4 w-4 text-muted-foreground"/><input value={v.seoOgImage} onChange={e=>setV({...v,seoOgImage:e.target.value})} placeholder="Image URL" className="field pl-9"/></div></Field><Field label="Google verification" hint="Optional"><input value={v.seoGoogleVerification} onChange={e=>setV({...v,seoGoogleVerification:e.target.value})} placeholder="Paste the verification token" className="field"/></Field>
     <label className="flex cursor-pointer items-center justify-between rounded-2xl border p-4"><div><p className="text-sm font-semibold">Hide website from search engines</p><p className="mt-1 text-xs text-muted-foreground">Adds a noindex directive. Keep this off for a public business website.</p></div><input type="checkbox" checked={v.seoNoIndex} onChange={e=>setV({...v,seoNoIndex:e.target.checked})} className="h-4 w-4"/></label>
     <button onClick={save} disabled={pending} className="rounded-xl bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground">{pending?"Saving…":"Save SEO settings"}</button>{msg&&<p className="text-xs font-medium text-primary">{msg}</p>}
    </div>
   </section>
   <aside className="space-y-5"><div className="rounded-3xl border bg-background p-6 shadow-sm"><div className="mb-4 flex items-center gap-2"><Globe2 className="h-4 w-4 text-primary"/><h2 className="text-sm font-bold">Google preview</h2></div><div className="rounded-2xl border bg-white p-5 dark:bg-card"><p className="truncate text-lg font-medium text-blue-700">{v.seoTitle||v.name}</p><p className="truncate text-xs text-emerald-700">{url}</p><p className="mt-1 line-clamp-3 text-sm text-muted-foreground">{v.seoDescription||"Your business description will appear here."}</p></div><div className="mt-4 flex items-start gap-2 text-xs text-muted-foreground"><Info className="mt-0.5 h-3.5 w-3.5 shrink-0"/>Search engines decide how and when to display snippets. These settings provide the correct signals; they cannot guarantee rankings.</div></div>
   <div className="rounded-3xl border bg-background p-6 shadow-sm"><h2 className="text-sm font-bold">SEO foundation</h2><div className="mt-4 space-y-3"><Check label="Clean storefront URLs"/><Check label="Business name and description"/><Check label="Mobile-friendly storefront"/><Check label="Structured business data"/><Check label="Sitemap-ready architecture"/><Check label="Social sharing metadata"/></div></div>
   <div className="rounded-3xl border bg-primary/5 p-5"><div className="flex gap-3"><MapPin className="h-5 w-5 text-primary"/><div><p className="text-sm font-semibold">Local SEO</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Keep your business address, phone, hours and location accurate in BizNest. Those details help search engines understand where you operate.</p></div></div></div>
   </aside>
  </div>
 </div>
}
function Field({label,hint,children}:{label:string;hint:string;children:ReactNode}){return <label className="grid gap-1.5"><div className="flex justify-between text-xs font-semibold"><span>{label}</span><span className="font-normal text-muted-foreground">{hint}</span></div>{children}</label>}
function Check({label}:{label:string}){return <div className="flex items-center gap-2 rounded-xl bg-muted/40 p-3 text-xs"><CheckCircle2 className="h-4 w-4 text-emerald-500"/>{label}</div>}
