"use client";
import { useState } from "react";
import { createAutomation, createApprovalRequest, decideApproval, createDocument, saveReportDefinition } from "@/lib/actions/business-platform";

export function WorkflowCenter({ slug, kind }: { slug:string; kind:"automations"|"approvals"|"documents"|"reports" }) {
 const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
 async function run(fn:()=>Promise<any>){setBusy(true);setMessage("");try{const r=await fn();setMessage(r?.success?"Saved successfully.":(r?.error??"Something went wrong."))}catch(e){setMessage("Request failed.")}finally{setBusy(false)}}
 if(kind==="automations") return <div className="rounded-2xl border bg-card p-6 space-y-4"><div><h2 className="font-semibold">Create automation</h2><p className="text-sm text-muted-foreground">Use only approved internal actions. No arbitrary code or external URL execution.</p></div><div className="grid gap-3 md:grid-cols-2"><input id="an" className="rounded-xl border bg-background p-3 text-sm" placeholder="Automation name"/><select id="at" className="rounded-xl border bg-background p-3 text-sm"><option>ORDER_CREATED</option><option>PAYMENT_RECEIVED</option><option>INVOICE_OVERDUE</option><option>INVENTORY_LOW</option><option>BOOKING_CONFIRMED</option></select></div><button disabled={busy} onClick={()=>{const n=(document.getElementById("an") as HTMLInputElement).value;const t=(document.getElementById("at") as HTMLSelectElement).value;return run(()=>createAutomation(slug,{name:n,trigger:t,actions:[{type:"NOTIFY_OWNER",title:n,body:`Automation triggered by ${t}.`}]}))}} className="rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">{busy?"Saving…":"Create automation"}</button>{message&&<p className="text-sm text-muted-foreground">{message}</p>}</div>;
 if(kind==="approvals") return <div className="rounded-2xl border bg-card p-6 space-y-4"><h2 className="font-semibold">Request approval</h2><input id="ap" className="w-full rounded-xl border bg-background p-3 text-sm" placeholder="What needs approval?"/><button disabled={busy} onClick={()=>run(()=>createApprovalRequest(slug,{title:(document.getElementById("ap") as HTMLInputElement).value,requestType:"GENERAL"}))} className="rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Create approval request</button>{message&&<p className="text-sm text-muted-foreground">{message}</p>}</div>;
 if(kind==="documents") return <div className="rounded-2xl border bg-card p-6 space-y-4"><h2 className="font-semibold">Add document</h2><div className="grid gap-3 md:grid-cols-2"><input id="dt" className="rounded-xl border bg-background p-3 text-sm" placeholder="Document title"/><input id="du" className="rounded-xl border bg-background p-3 text-sm" placeholder="Secure file URL"/></div><button disabled={busy} onClick={()=>run(()=>createDocument(slug,{title:(document.getElementById("dt") as HTMLInputElement).value,documentType:"GENERAL",fileUrl:(document.getElementById("du") as HTMLInputElement).value}))} className="rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Save document</button>{message&&<p className="text-sm text-muted-foreground">{message}</p>}</div>;
 return <div className="rounded-2xl border bg-card p-6 space-y-4"><h2 className="font-semibold">Save report</h2><div className="grid gap-3 md:grid-cols-2"><input id="rn" className="rounded-xl border bg-background p-3 text-sm" placeholder="Report name"/><select id="rs" className="rounded-xl border bg-background p-3 text-sm"><option value="orders">Orders</option><option value="products">Products</option><option value="customers">Customers</option><option value="payments">Payments</option></select></div><button disabled={busy} onClick={()=>run(()=>saveReportDefinition(slug,{name:(document.getElementById("rn") as HTMLInputElement).value,source:(document.getElementById("rs") as HTMLSelectElement).value,fields:["id","createdAt"],filters:[],groupBy:[]}))} className="rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Save report definition</button>{message&&<p className="text-sm text-muted-foreground">{message}</p>}</div>;
}
