import { notFound } from "next/navigation";
import Link from "next/link";
import { CalendarDays, Moon, Users, BedDouble, Search } from "lucide-react";
import { getStoreBranding } from "@/lib/actions/store-branding";
import { listStoreBookings } from "@/lib/actions/account";
import { getHotelContent } from "@/lib/hotel-content";
import { VelouraAccountHero } from "@/components/storefront/veloura-account-shell";
const date=(v:Date|string)=>new Date(v).toLocaleDateString(undefined,{day:"2-digit",month:"short",year:"numeric"});
const money=(v:any,c="NGN")=>`${c==="NGN"?"₦":c+" "}${Number(v||0).toLocaleString()}`;
export default async function Page({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const[store,bookings,hotel]=await Promise.all([getStoreBranding(slug),listStoreBookings(slug),getHotelContent(slug)]);if(!store)notFound();const hero=hotel.rooms.find((r:any)=>r.featured)?.image||hotel.rooms[0]?.image||null;const upcoming=bookings.filter((b:any)=>b.status!=="CANCELLED"&&new Date(b.checkOut??b.scheduledAt)>=new Date());const completed=bookings.filter((b:any)=>!upcoming.some((u:any)=>u.id===b.id)&&b.status!=="CANCELLED");const cancelled=bookings.filter((b:any)=>b.status==="CANCELLED");return <div className="veloura-account-content"><VelouraAccountHero title="My Bookings" subtitle="View and manage all your bookings in one place." image={hero}/><div className="veloura-page-tools"><div className="veloura-tabs"><span className="active">All Bookings ({bookings.length})</span><span>Upcoming ({upcoming.length})</span><span>Completed ({completed.length})</span><span>Cancelled ({cancelled.length})</span></div><Link className="veloura-gold-btn" href={`/store/${slug}/booking`}>Book a New Stay →</Link></div><div className="veloura-page-tools"><div/><div className="veloura-search"><Search size={16}/><input placeholder="Search your bookings..."/></div></div>{bookings.length?bookings.map((b:any)=><article className="veloura-list-card" key={b.id}><img src={b.service.images?.[0]||hero||""} alt=""/><div><h2>{b.service.name}<span className="veloura-badge" style={{marginLeft:10}}>{b.status}</span></h2><p>Reservation ID: {b.id}</p><div className="veloura-icon-row"><span><CalendarDays/> {b.checkIn&&b.checkOut?`${date(b.checkIn)} – ${date(b.checkOut)}`:date(b.scheduledAt)}</span><span><Moon/> {b.checkIn&&b.checkOut?`${Math.max(1,Math.ceil((new Date(b.checkOut).getTime()-new Date(b.checkIn).getTime())/86400000))} Nights`:`${b.durationMins} min`}</span><span><Users/> {b.partySize||"—"} Guests</span><span><BedDouble/> {(b.service as any).attributes?.bedType||"—"}</span></div></div><div className="veloura-card-actions"><strong style={{fontSize:20,textAlign:"right"}}>{money(b.paymentAmount||b.service.price,b.paymentCurrency||b.service.currency)}</strong><small style={{color:b.paymentStatus==="PAID"?"#28794b":"#9a6b2b",textAlign:"right"}}>{b.paymentStatus === "PAID" ? "Payment confirmed" : "Payment pending"}</small><Link href={`/store/${slug}/account/bookings/${b.id}`}>View Details</Link>{b.status!=="CANCELLED"&&<Link href={`/store/${slug}/account/messages`}>{upcoming.some((u:any)=>u.id===b.id)?"Request changes":"Book again"}</Link>}</div></article>):<div className="veloura-empty">No bookings yet. <Link href={`/store/${slug}/booking`}>Book your first stay →</Link></div>}</div>}
