import React from "react";
import { AccountLink } from "@/components/storefront/account-link";
import { CartLink } from "@/components/storefront/cart-link";
import type { TemplateTheme } from "@/lib/template-themes";

type CatalogItem = { id:string; kind:"product"|"service"; name:string; description:string|null; price:number; currency:string; image:string|null; categoryName:string|null; type:string; rentalUnit:string|null; isBookable:boolean };
type Props = { store:any; slug:string; catalogItems:CatalogItem[]; goodReviews:any[]; avgRating:number|null; completedOrders:number; social:Record<string,string>; theme:TemplateTheme & { professionalMode?: string } };

const MODES = [
  "graphic-design","branding-agency","marketing-agency","photography-studio","consulting","accounting","legal","hr-recruitment","web-development","it-services","architecture","engineering","construction-company",
] as const;

type Mode = typeof MODES[number];

const COPY: Record<Mode,{eyebrow:string;headline:string;sub:string;cta:string;services:string[];stat1:string;stat2:string;stat3:string;}> = {
  "graphic-design": {eyebrow:"CREATIVE / PRINT / PRODUCTION",headline:"Ideas, made tangible.",sub:"A premium creative and print studio for brands that care how every detail looks, feels and lands in the real world.",cta:"Start a project",services:["Brand identity","Campaign design","Premium print","Packaging"],stat1:"Projects delivered",stat2:"Print formats",stat3:"Client approvals"},
  "branding-agency": {eyebrow:"BRAND STRATEGY / IDENTITY / CULTURE",headline:"Make your brand unmistakable.",sub:"Strategic identity systems, art direction and brand worlds designed to create recognition before a word is spoken.",cta:"Enquire about branding",services:["Brand strategy","Visual identity","Art direction","Brand guidelines"],stat1:"Brand systems",stat2:"Markets launched",stat3:"Avg. engagement"},
  "marketing-agency": {eyebrow:"STRATEGY / CAMPAIGNS / GROWTH",headline:"Marketing with a point of view.",sub:"Campaigns, digital experiences and growth systems for ambitious brands that want measurable momentum without losing their character.",cta:"Plan a campaign",services:["Campaign strategy","Performance marketing","Content systems","Growth consulting"],stat1:"Campaigns",stat2:"Markets",stat3:"Growth stories"},
  "photography-studio": {eyebrow:"EDITORIAL / COMMERCIAL / PORTRAIT",headline:"Light, captured with intention.",sub:"A cinematic studio for portraits, brands, products and campaigns — built around beautiful images and an effortless client experience.",cta:"Book a session",services:["Brand photography","Portraits","Product studio","Editorial"],stat1:"Sessions",stat2:"Brands photographed",stat3:"Final frames"},
  consulting: {eyebrow:"ADVISORY / STRATEGY / TRANSFORMATION",headline:"Clarity for consequential decisions.",sub:"Independent thinking, practical strategy and executive advisory for leaders navigating complex decisions and meaningful change.",cta:"Book a consultation",services:["Strategy advisory","Business transformation","Market intelligence","Executive workshops"],stat1:"Engagements",stat2:"Industries",stat3:"Senior advisors"},
  accounting: {eyebrow:"FINANCE / TAX / ASSURANCE",headline:"Numbers you can trust.",sub:"Modern accounting and financial advisory for businesses that want clean books, clear decisions and confidence at every stage.",cta:"Request a consultation",services:["Accounting","Tax advisory","Financial reporting","Business advisory"],stat1:"Businesses served",stat2:"Reports delivered",stat3:"Years of expertise"},
  legal: {eyebrow:"COUNSEL / COMMERCIAL / DISPUTE",headline:"Counsel when it matters.",sub:"A discreet legal practice focused on commercial clarity, strong representation and advice that protects what you are building.",cta:"Request a consultation",services:["Corporate counsel","Contracts","Dispute resolution","Intellectual property"],stat1:"Matters handled",stat2:"Practice areas",stat3:"Client relationships"},
  "hr-recruitment": {eyebrow:"PEOPLE / TALENT / CULTURE",headline:"The right people change everything.",sub:"Executive search, recruitment and people strategy for companies building teams capable of their next chapter.",cta:"Hire with us",services:["Executive search","Talent acquisition","People strategy","Employer branding"],stat1:"Placements",stat2:"Talent network",stat3:"Partner companies"},
  "web-development": {eyebrow:"DIGITAL PRODUCTS / WEB / SOFTWARE",headline:"Digital products that move businesses forward.",sub:"Strategy, design and engineering for high-performance websites and software that feel as good as they work.",cta:"Start a digital project",services:["Web platforms","Product design","Software engineering","Growth systems"],stat1:"Products shipped",stat2:"Lighthouse-ready",stat3:"Partner teams"},
  "it-services": {eyebrow:"INFRASTRUCTURE / SECURITY / SUPPORT",headline:"Technology, without the noise.",sub:"Reliable IT infrastructure, cybersecurity and managed support for teams that need technology to simply work.",cta:"Talk to an engineer",services:["Managed IT","Cybersecurity","Cloud infrastructure","Technical support"],stat1:"Systems managed",stat2:"Uptime target",stat3:"Support response"},
  architecture: {eyebrow:"ARCHITECTURE / INTERIORS / PLACE",headline:"Spaces with a sense of permanence.",sub:"Architecture and interiors shaped by proportion, material, light and the way people actually live and work.",cta:"Discuss a project",services:["Architecture","Interior design","Spatial strategy","Project delivery"],stat1:"Projects",stat2:"Square metres",stat3:"Cities"},
  engineering: {eyebrow:"ENGINEERING / SYSTEMS / DELIVERY",headline:"Precision behind the build.",sub:"Engineering services that bring technical confidence to complex projects — from concept through delivery.",cta:"Request an engineering review",services:["Civil engineering","Structural engineering","MEP systems","Technical consulting"],stat1:"Projects",stat2:"Disciplines",stat3:"Safety-first"},
  "construction-company": {eyebrow:"CONSTRUCTION / RENOVATION / DELIVERY",headline:"Built properly. Built to last.",sub:"A construction partner for homes, commercial spaces and complex renovations — with clear process from estimate to handover.",cta:"Request a quote",services:["New builds","Renovations","Fit-outs","Project management"],stat1:"Projects delivered",stat2:"Trades coordinated",stat3:"On-time focus"},
};

function money(x:CatalogItem){return `${x.currency} ${x.price.toLocaleString()}`}
function itemHref(slug:string,x:CatalogItem){return `/store/${slug}/${x.kind}/${x.id}`}
function img(url:string|null, fallback:string):React.CSSProperties{return url?{backgroundImage:`url(${url})`,backgroundSize:"cover",backgroundPosition:"center"}:{background:fallback}}
function Logo({store,light=false}:{store:any;light?:boolean}){return store.logoUrl?<img src={store.logoUrl} alt={store.name} style={{width:42,height:42,objectFit:"contain"}}/>:<span style={{width:42,height:42,borderRadius:12,display:"grid",placeItems:"center",background:light?"#fff":"#111",color:light?"#111":"#fff",fontWeight:900}}>{store.name?.[0]}</span>}
function Header({store,slug,theme,light=false,label="Services"}:{store:any;slug:string;theme:any;light?:boolean;label?:string}){return <header style={{position:"sticky",top:0,zIndex:30,background:light?"rgba(10,10,10,.84)":"rgba(255,255,255,.88)",color:light?"#fff":theme.ink,backdropFilter:"blur(18px)",borderBottom:`1px solid ${light?"#ffffff1f":theme.border||"#00000014"}`}}><div style={{maxWidth:1360,margin:"auto",padding:"16px 28px",display:"flex",alignItems:"center",gap:20}}><a href={`/store/${slug}`} style={{display:"flex",alignItems:"center",gap:10,fontWeight:800,letterSpacing:"-.02em"}}><Logo store={store} light={light}/><span>{store.name}</span></a><nav style={{marginLeft:"auto",display:"flex",alignItems:"center",gap:20,fontSize:12,fontWeight:700}}><a href={`/store/${slug}/catalog`}>{label}</a><a href={`/store/${slug}/start-project`}>Start a project</a><a href={`/store/${slug}/search`}>Search</a>{store.sellsProducts&&<CartLink storeSlug={slug} accent={theme.accent} onAccent={light?"#111":"#fff"} ink={light?"#fff":theme.ink}/>}<AccountLink storeSlug={slug} ink={light?"#fff":theme.ink}/></nav></div></header>}

export function ProfessionalServicesStorefront(props:Props){
 const {store,slug,catalogItems,goodReviews,avgRating,completedOrders,theme}=props; const mode=(theme.professionalMode||"") as Mode; const c=COPY[mode]; if(!c) return null;
 const hero=store.bannerUrl||null; const items=catalogItems.slice(0,8); const accent=theme.accent; const ink=theme.ink; const bg=theme.bg; const muted=theme.muted||`${ink}99`;
 const common={"--ps-accent":accent,"--ps-ink":ink,"--ps-muted":muted,"--ps-bg":bg,"--ps-card":theme.card||"#fff","--ps-border":theme.border||`${ink}18`} as React.CSSProperties;
 const card=(x:CatalogItem,i:number)=> <a key={x.id} href={itemHref(slug,x)} style={{display:"block",textDecoration:"none",color:"inherit"}}><div style={{aspectRatio:"4/3",...img(x.image,`${accent}${i%2?"18":"28"}`),borderRadius:theme.radius||18}}/><div style={{paddingTop:12}}><small style={{color:muted,textTransform:"uppercase",letterSpacing:".14em",fontSize:9,fontWeight:800}}>{x.categoryName||x.kind}</small><h3 style={{margin:"7px 0 5px",fontSize:18}}>{x.name}</h3><p style={{margin:0,color:muted,fontSize:12,lineHeight:1.6}}>{x.description||c.sub}</p><b style={{display:"block",marginTop:8,fontSize:12}}>{money(x)}{x.isBookable?" · Bookable":""}</b></div></a>;
 const Review=goodReviews[0];
 const CTA=({text=c.cta,dark=false}:{text?:string;dark?:boolean})=><a href={`/store/${slug}/start-project`} style={{display:"inline-flex",alignItems:"center",gap:10,padding:"14px 20px",background:dark?"#fff":accent,color:dark?"#111":"#fff",borderRadius:theme.radius||12,fontSize:12,fontWeight:850,textDecoration:"none"}}>{text}<span>↗</span></a>;
 const stats=<div className="bn-grid-2" style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:1,background:`${ink}16`,border:`1px solid ${ink}16`}}>{[c.stat1,c.stat2,c.stat3].map((s,i)=><div key={s} style={{padding:"22px 18px",background:bg}}><b style={{fontSize:26,display:"block"}}>{i===0?catalogItems.length:i===1?(avgRating?.toFixed(1)||"4.9"):(completedOrders||"24+")}</b><span style={{fontSize:10,color:muted,textTransform:"uppercase",letterSpacing:".14em"}}>{s}</span></div>)}</div>;

 if(mode==="graphic-design") return <div style={{...common,fontFamily:theme.font,background:bg,color:ink}}><Header store={store} slug={slug} theme={theme} label="Work"/><main><section className="bn-2col" style={{minHeight:720,display:"grid",gridTemplateColumns:"1.05fr .95fr",background:"#111",color:"#fff"}}><div style={{padding:"clamp(60px,8vw,120px) clamp(24px,6vw,90px)",display:"flex",flexDirection:"column",justifyContent:"center"}}><div style={{color:accent,fontSize:10,fontWeight:900,letterSpacing:".24em"}}>{c.eyebrow}</div><h1 style={{fontFamily:theme.headlineFont,fontSize:"clamp(58px,8vw,120px)",lineHeight:.86,letterSpacing:"-.06em",margin:"20px 0"}}>{c.headline}</h1><p style={{maxWidth:560,color:"#ffffffb8",lineHeight:1.8,fontSize:16}}>{store.business?.description||c.sub}</p><div style={{marginTop:30}}><CTA dark/></div></div><div style={{minHeight:520,...img(hero,`linear-gradient(145deg,${accent},#221f1c)`),backgroundPosition:"center"}}/></section><section style={{padding:"90px 6vw",background:"#f5f0e8"}}><div style={{maxWidth:1320,margin:"auto"}}><p style={{fontSize:11,letterSpacing:".2em",fontWeight:900}}>THE STUDIO</p><h2 style={{fontFamily:theme.headlineFont,fontSize:"clamp(38px,5vw,70px)",maxWidth:800,margin:"14px 0 45px"}}>Design that survives the screen and the shelf.</h2>{stats}</div></section><section style={{padding:"100px 6vw"}}><div style={{maxWidth:1320,margin:"auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",marginBottom:30}}><div><small style={{color:accent,fontWeight:900,letterSpacing:".16em"}}>SELECTED WORK / SERVICES</small><h2 style={{fontFamily:theme.headlineFont,fontSize:46,margin:"8px 0"}}>The workbench.</h2></div><a href={`/store/${slug}/catalog`}>View all ↗</a></div><div className="bn-grid-2" style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:20}}>{items.slice(0,4).map(card)}</div></div></section><section style={{padding:"100px 6vw",background:"#111",color:"#fff"}}><div style={{maxWidth:1000,margin:"auto",textAlign:"center"}}><p style={{color:accent,letterSpacing:".2em",fontSize:10,fontWeight:900}}>FROM BRIEF TO PRODUCTION</p><h2 style={{fontFamily:theme.headlineFont,fontSize:"clamp(42px,6vw,78px)",lineHeight:1,margin:"15px 0 30px"}}>Brief → Design → Approve → Print → Deliver.</h2><CTA dark text="Build a project with us"/></div></section></main><Footer store={store} theme={theme}/></div>;

 if(mode==="branding-agency") return <div style={{...common,fontFamily:theme.font,background:bg,color:ink}}><Header store={store} slug={slug} theme={theme}/><main><section style={{padding:"110px 6vw 80px",borderBottom:`1px solid ${theme.border}`}}><div style={{maxWidth:1350,margin:"auto"}}><div style={{fontSize:11,letterSpacing:".22em",fontWeight:900,color:accent}}>{c.eyebrow}</div><h1 style={{fontSize:"clamp(64px,11vw,170px)",lineHeight:.82,letterSpacing:"-.075em",maxWidth:1200,margin:"24px 0 50px"}}>Make your<br/><span style={{fontFamily:theme.headlineFont,fontStyle:"italic"}}>brand</span> unmistakable.</h1><div style={{display:"flex",justifyContent:"space-between",gap:30,alignItems:"end"}}><p style={{maxWidth:560,color:muted,lineHeight:1.8}}>{store.business?.description||c.sub}</p><CTA text="Enquire"/></div></div></section><section style={{padding:"70px 6vw"}}><div className="bn-2col" style={{maxWidth:1350,margin:"auto",display:"grid",gridTemplateColumns:".7fr 1.3fr",gap:70}}><div><small style={{color:accent,fontWeight:900}}>01 — WHAT WE DO</small><h2 style={{fontFamily:theme.headlineFont,fontSize:54,lineHeight:1,marginTop:15}}>A complete visual world.</h2></div><div className="bn-2col" style={{display:"grid",gridTemplateColumns:"1fr 1fr"}}>{c.services.map((s,i)=><div key={s} style={{padding:"26px 10px",borderTop:`1px solid ${theme.border}`,fontSize:20}}><span style={{color:accent,fontSize:10}}>0{i+1}</span><div style={{marginTop:12}}>{s}</div></div>)}</div></div></section><section style={{padding:"70px 6vw",background:"#111",color:"#fff"}}><div style={{maxWidth:1350,margin:"auto"}}><small style={{color:accent,letterSpacing:".2em"}}>CASE STUDIES</small><h2 style={{fontFamily:theme.headlineFont,fontSize:56,margin:"12px 0 35px"}}>Selected identities.</h2><div className="bn-2col" style={{display:"grid",gridTemplateColumns:"1.4fr .8fr .8fr",gap:12}}>{items.slice(0,3).map((x,i)=><a key={x.id} href={itemHref(slug,x)} style={{minHeight:i===0?520:340,...img(x.image,`linear-gradient(135deg,${accent}${i?"55":"99"},#222)`),padding:22,display:"flex",alignItems:"end",color:"#fff"}}><div><small>{x.categoryName||"CASE STUDY"}</small><h3 style={{fontSize:26,margin:"6px 0"}}>{x.name}</h3></div></a>)}</div></div></section><section style={{padding:"100px 6vw",textAlign:"center"}}><h2 style={{fontFamily:theme.headlineFont,fontSize:64,marginBottom:25}}>Ready to be remembered?</h2><CTA/></section></main><Footer store={store} theme={theme}/></div>;

 if(mode==="marketing-agency") return <div style={{...common,fontFamily:theme.font,background:"#eef4ff",color:ink}}><Header store={store} slug={slug} theme={theme}/><main><section style={{padding:"70px 5vw 90px",background:"#173bff",color:"#fff"}}><div style={{maxWidth:1300,margin:"auto"}}><div style={{fontSize:10,letterSpacing:".22em",fontWeight:900}}>{c.eyebrow}</div><h1 style={{fontSize:"clamp(58px,9vw,128px)",lineHeight:.86,letterSpacing:"-.07em",maxWidth:1050,margin:"25px 0"}}>{c.headline}</h1><p style={{maxWidth:620,fontSize:17,lineHeight:1.7,color:"#ffffffcc"}}>{store.business?.description||c.sub}</p><div style={{marginTop:28}}><CTA dark text={c.cta}/></div></div></section><section style={{padding:"50px 5vw"}}><div style={{maxWidth:1300,margin:"auto"}}><div className="bn-grid-2" style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14}}>{["Reach","Engagement","Conversion","Retention"].map((x,i)=><div key={x} style={{background:"#fff",padding:22,borderRadius:18,boxShadow:"0 15px 40px #173bff0f"}}><small style={{color:"#667085"}}>{x}</small><b style={{display:"block",fontSize:32,marginTop:12}}>{["284K","8.7%","12.4%","91%"][i]}</b><span style={{fontSize:10,color:"#12a150"}}>↑ 18.4%</span></div>)}</div></div></section><section style={{padding:"70px 5vw"}}><div style={{maxWidth:1300,margin:"auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",marginBottom:28}}><div><small style={{color:"#173bff",fontWeight:900}}>CAMPAIGN LAB</small><h2 style={{fontSize:48,margin:"8px 0"}}>What we can build.</h2></div><a href={`/store/${slug}/catalog`}>Explore services ↗</a></div><div className="bn-grid-2" style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:18}}>{items.slice(0,6).map(card)}</div></div></section><section style={{padding:"90px 5vw",background:"#101828",color:"#fff"}}><div style={{maxWidth:1000,margin:"auto",display:"flex",justifyContent:"space-between",alignItems:"center",gap:30}}><div><small style={{color:"#8aa0ff"}}>NEXT MOVE</small><h2 style={{fontSize:52,margin:"10px 0"}}>Let's make the numbers interesting.</h2></div><CTA dark/></div></section></main><Footer store={store} theme={{...theme,bg:"#101828",ink:"#fff",muted:"#98a2b3",border:"#ffffff18"}}/></div>;

 if(mode==="photography-studio") return <div style={{...common,fontFamily:theme.font,background:"#0b0b0b",color:"#fff"}}><Header store={store} slug={slug} theme={{...theme,ink:"#fff",bg:"#0b0b0b",border:"#ffffff20"}} light label="Portfolio"/><main><section style={{minHeight:800,padding:"80px 5vw",position:"relative",...img(hero,"linear-gradient(135deg,#222,#777)"),display:"flex",alignItems:"end"}}><div style={{position:"absolute",inset:0,background:"linear-gradient(0deg,#000 0%,transparent 65%)"}}/><div style={{position:"relative",maxWidth:1000}}><small style={{color:accent,letterSpacing:".22em",fontWeight:900}}>{c.eyebrow}</small><h1 style={{fontFamily:theme.headlineFont,fontSize:"clamp(62px,10vw,145px)",lineHeight:.84,margin:"18px 0",letterSpacing:"-.06em"}}>{c.headline}</h1><p style={{maxWidth:600,color:"#ffffffaa",lineHeight:1.8}}>{store.business?.description||c.sub}</p><div style={{marginTop:28}}><CTA dark text={c.cta}/></div></div></section><section style={{padding:"80px 5vw"}}><div style={{maxWidth:1400,margin:"auto",display:"flex",gap:10,overflowX:"auto",paddingBottom:20}}>{items.map((x,i)=><a key={x.id} href={itemHref(slug,x)} style={{minWidth:i===0?520:360,height:i===0?520:420,...img(x.image,`linear-gradient(135deg,#222,#555)`),display:"flex",alignItems:"end",padding:20,color:"#fff"}}><div><small style={{color:accent}}>{x.categoryName||"WORK"}</small><h3 style={{fontSize:24,margin:5}}>{x.name}</h3></div></a>)}</div></section><section style={{padding:"90px 5vw",background:"#f4f1eb",color:"#161616"}}><div className="bn-2col" style={{maxWidth:1100,margin:"auto",display:"grid",gridTemplateColumns:"1fr 1fr",gap:60}}><div><small style={{color:accent}}>THE STUDIO</small><h2 style={{fontFamily:theme.headlineFont,fontSize:60}}>Quiet direction. Strong images.</h2></div><div><p style={{lineHeight:1.9,color:"#666"}}>{c.sub}</p><div style={{marginTop:25}}>{stats}</div></div></div></section><section style={{padding:"90px 5vw",textAlign:"center"}}><h2 style={{fontFamily:theme.headlineFont,fontSize:64}}>Have a story to tell?</h2><div style={{marginTop:25}}><CTA dark/></div></section></main><Footer store={store} theme={{...theme,bg:"#0b0b0b",ink:"#fff",muted:"#999",border:"#ffffff18"}}/></div>;

 if(mode==="consulting") return <div style={{...common,fontFamily:theme.font,background:"#f3f1eb",color:"#15202b"}}><Header store={store} slug={slug} theme={{...theme,ink:"#15202b",bg:"#f3f1eb"}}/><main><section style={{padding:"110px 6vw 80px",background:"#15202b",color:"#fff"}}><div className="bn-2col" style={{maxWidth:1300,margin:"auto",display:"grid",gridTemplateColumns:"1.2fr .8fr",gap:70}}><div><small style={{color:"#c5a46d",letterSpacing:".22em"}}>{c.eyebrow}</small><h1 style={{fontFamily:theme.headlineFont,fontSize:"clamp(58px,8vw,110px)",lineHeight:.9,margin:"20px 0"}}>{c.headline}</h1><p style={{maxWidth:580,color:"#ffffffaa",lineHeight:1.8}}>{store.business?.description||c.sub}</p><div style={{marginTop:28}}><CTA dark/></div></div><div style={{alignSelf:"end",borderLeft:"1px solid #ffffff2a",paddingLeft:30}}><small style={{color:"#ffffff88"}}>ADVISORY NOTE</small><p style={{fontFamily:theme.headlineFont,fontSize:30,lineHeight:1.25}}>The best strategy is the one a team can actually execute.</p></div></div></section><section style={{padding:"75px 6vw"}}><div style={{maxWidth:1300,margin:"auto"}}>{stats}</div></section><section style={{padding:"75px 6vw"}}><div className="bn-2col" style={{maxWidth:1300,margin:"auto",display:"grid",gridTemplateColumns:".7fr 1.3fr",gap:60}}><div><small style={{color:"#a88345"}}>02 — CAPABILITIES</small><h2 style={{fontFamily:theme.headlineFont,fontSize:54}}>Where we add leverage.</h2></div><div>{c.services.map((s,i)=><a key={s} href={`/store/${slug}/catalog`} style={{display:"flex",justifyContent:"space-between",padding:"24px 0",borderBottom:"1px solid #15202b22"}}><span>{s}</span><span>0{i+1} ↗</span></a>)}</div></div></section><section style={{padding:"100px 6vw",background:"#c5a46d",color:"#15202b",textAlign:"center"}}><h2 style={{fontFamily:theme.headlineFont,fontSize:64}}>Bring us the difficult question.</h2><div style={{marginTop:25}}><CTA text="Book a consultation"/></div></section></main><Footer store={store} theme={{...theme,bg:"#15202b",ink:"#fff",muted:"#aab4bd",border:"#ffffff18"}}/></div>;

 if(mode==="accounting") return <div style={{...common,fontFamily:theme.font,background:"#f4f7f2",color:"#163b2c"}}><Header store={store} slug={slug} theme={{...theme,ink:"#163b2c",bg:"#f4f7f2"}}/><main><section style={{padding:"90px 5vw",background:"#0e3b2b",color:"#fff"}}><div className="bn-2col" style={{maxWidth:1300,margin:"auto",display:"grid",gridTemplateColumns:"1fr .7fr",gap:60,alignItems:"end"}}><div><small style={{color:"#8fcea9",letterSpacing:".22em"}}>{c.eyebrow}</small><h1 style={{fontFamily:theme.headlineFont,fontSize:"clamp(58px,8vw,110px)",lineHeight:.9,margin:"18px 0"}}>{c.headline}</h1><p style={{maxWidth:600,color:"#ffffffb0",lineHeight:1.8}}>{store.business?.description||c.sub}</p></div><div style={{background:"#ffffff12",padding:28,border:"1px solid #ffffff18"}}><small>THIS MONTH</small><b style={{display:"block",fontSize:48,margin:"8px 0"}}>₦24.8m</b><span style={{color:"#8fcea9"}}>↑ 14.2% cash flow</span></div></div></section><section style={{padding:"65px 5vw"}}><div style={{maxWidth:1300,margin:"auto"}}>{stats}</div></section><section style={{padding:"80px 5vw"}}><div style={{maxWidth:1300,margin:"auto"}}><small style={{color:"#26805a",letterSpacing:".18em"}}>SERVICES</small><h2 style={{fontFamily:theme.headlineFont,fontSize:54}}>Financial confidence, built in.</h2><div className="bn-2col" style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:16,marginTop:30}}>{c.services.map((s,i)=><a key={s} href={`/store/${slug}/catalog`} style={{padding:30,background:"#fff",border:"1px solid #163b2c12",borderRadius:16}}><span style={{fontSize:10,color:"#26805a"}}>0{i+1}</span><h3 style={{fontSize:24,margin:"12px 0"}}>{s}</h3><p style={{color:muted,lineHeight:1.7}}>Structured support for decisions that deserve accurate numbers.</p></a>)}</div></div></section><section style={{padding:"85px 5vw",background:"#e2eee5",textAlign:"center"}}><h2 style={{fontFamily:theme.headlineFont,fontSize:60}}>Know your numbers. Own your next move.</h2><div style={{marginTop:25}}><CTA text="Request a consultation"/></div></section></main><Footer store={store} theme={{...theme,bg:"#0e3b2b",ink:"#fff",muted:"#a8b8b0",border:"#ffffff18"}}/></div>;

 // The remaining professional disciplines intentionally use different visual languages.
 const dark = mode==="web-development"||mode==="it-services"||mode==="legal"||mode==="engineering"||mode==="construction-company";
 const palettes:Record<string,{bg:string;surface:string;accent:string;ink:string}>={
   legal:{bg:"#f4efe7",surface:"#201416",accent:"#b38a4b",ink:"#241719"},
   "hr-recruitment":{bg:"#eef5ff",surface:"#0d5cff",accent:"#0d5cff",ink:"#10233f"},
   "web-development":{bg:"#07090d",surface:"#10141c",accent:"#7cff67",ink:"#f2f6ff"},
   "it-services":{bg:"#07111f",surface:"#0d1d33",accent:"#4cc9f0",ink:"#f3f8ff"},
   architecture:{bg:"#e9e4da",surface:"#1f211f",accent:"#9a7952",ink:"#252522"},
   engineering:{bg:"#edf0f1",surface:"#17232b",accent:"#d28a32",ink:"#182329"},
   "construction-company":{bg:"#deddd8",surface:"#171817",accent:"#f28b30",ink:"#1d1e1b"},
 };
 const p=palettes[mode]||palettes.legal;
 const serviceList=<div className="bn-2col" style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:1,background:`${p.ink}20`}}>{c.services.map((s,i)=><a key={s} href={`/store/${slug}/catalog`} style={{background:p.bg,color:p.ink,padding:26,textDecoration:"none"}}><small style={{color:p.accent}}>0{i+1}</small><h3 style={{fontSize:21,margin:"9px 0"}}>{s}</h3><span style={{fontSize:11,opacity:.6}}>Explore service ↗</span></a>)}</div>;

 if(mode==="legal") return <div style={{fontFamily:theme.font,background:p.bg,color:p.ink}}><Header store={store} slug={slug} theme={{...theme,ink:p.ink,bg:p.bg,accent:p.accent}}/><main><section style={{padding:"110px 6vw",background:p.surface,color:"#fff"}}><div style={{maxWidth:1200,margin:"auto"}}><small style={{color:p.accent,letterSpacing:".22em"}}>{c.eyebrow}</small><h1 style={{fontFamily:theme.headlineFont,fontSize:"clamp(60px,9vw,130px)",lineHeight:.84,maxWidth:900,margin:"20px 0"}}>{c.headline}</h1><p style={{maxWidth:570,color:"#ffffffaa",lineHeight:1.8}}>{c.sub}</p><div style={{marginTop:28}}><CTA dark/></div></div></section><section style={{padding:"80px 6vw"}}><div className="bn-2col" style={{maxWidth:1200,margin:"auto",display:"grid",gridTemplateColumns:".6fr 1.4fr",gap:70}}><div><small style={{color:p.accent}}>PRACTICE</small><h2 style={{fontFamily:theme.headlineFont,fontSize:52}}>Measured advice. Serious representation.</h2></div><div>{serviceList}</div></div></section><section style={{padding:"90px 6vw",background:"#e7dfd2"}}><div style={{maxWidth:900,margin:"auto",textAlign:"center"}}><div style={{fontSize:40}}>“</div><p style={{fontFamily:theme.headlineFont,fontSize:34,lineHeight:1.2}}>{Review?.comment||"Discreet, thoughtful counsel from people who understand what is at stake."}</p><small>{Review?.author?.name||"Client"}</small></div></section></main><Footer store={store} theme={{...theme,bg:p.surface,ink:"#fff",muted:"#aaa",border:"#ffffff18"}}/></div>;

 if(mode==="hr-recruitment") return <div style={{fontFamily:theme.font,background:p.bg,color:p.ink}}><Header store={store} slug={slug} theme={{...theme,ink:p.ink,bg:p.bg,accent:p.accent}}/><main><section style={{padding:"80px 5vw",background:"#0d5cff",color:"#fff",borderRadius:"0 0 50px 50px"}}><div style={{maxWidth:1300,margin:"auto"}}><small style={{letterSpacing:".2em"}}>{c.eyebrow}</small><h1 style={{fontSize:"clamp(60px,10vw,140px)",lineHeight:.82,letterSpacing:"-.07em",maxWidth:1000,margin:"25px 0"}}>{c.headline}</h1><p style={{maxWidth:600,lineHeight:1.8,color:"#ffffffc7"}}>{c.sub}</p><div style={{marginTop:28}}><CTA dark text={c.cta}/></div></div></section><section style={{padding:"65px 5vw"}}><div style={{maxWidth:1300,margin:"auto"}}>{stats}</div></section><section style={{padding:"75px 5vw"}}><div style={{maxWidth:1300,margin:"auto"}}><div style={{display:"flex",justifyContent:"space-between"}}><h2 style={{fontSize:48}}>Open opportunities</h2><a href={`/store/${slug}/catalog`}>View roles ↗</a></div><div style={{marginTop:25,display:"grid",gap:12}}>{items.slice(0,5).map((x,i)=><a key={x.id} href={itemHref(slug,x)} style={{background:"#fff",padding:"22px 25px",borderRadius:18,display:"flex",justifyContent:"space-between",alignItems:"center",boxShadow:"0 10px 30px #0d5cff0b"}}><div><small style={{color:p.accent}}>{x.categoryName||"OPEN ROLE"}</small><h3 style={{margin:"5px 0"}}>{x.name}</h3></div><span>View role →</span></a>)}</div></div></section><section style={{padding:"80px 5vw",background:"#10233f",color:"#fff",textAlign:"center"}}><h2 style={{fontSize:56}}>Build the team your next chapter deserves.</h2><div style={{marginTop:25}}><CTA dark text="Partner with us"/></div></section></main><Footer store={store} theme={{...theme,bg:"#10233f",ink:"#fff",muted:"#a9b6c8",border:"#ffffff18"}}/></div>;

 if(mode==="web-development") return <div style={{fontFamily:theme.font,background:p.bg,color:p.ink}}><Header store={store} slug={slug} theme={{...theme,ink:p.ink,bg:p.bg,accent:p.accent}} light label="Projects"/><main><section style={{padding:"90px 5vw",borderBottom:"1px solid #ffffff14"}}><div style={{maxWidth:1300,margin:"auto"}}><div style={{fontFamily:"monospace",fontSize:11,color:p.accent}}>{"// DIGITAL PRODUCT STUDIO"}</div><h1 style={{fontSize:"clamp(58px,9vw,130px)",lineHeight:.83,letterSpacing:"-.07em",maxWidth:1000,margin:"20px 0"}}>{c.headline}</h1><p style={{maxWidth:600,color:"#aab3c2",lineHeight:1.8}}>{c.sub}</p><div style={{marginTop:28}}><CTA dark text="Start a build"/></div></div></section><section style={{padding:"70px 5vw",background:"#0d1016"}}><div style={{maxWidth:1300,margin:"auto"}}><div style={{fontFamily:"monospace",color:p.accent,fontSize:11}}>const capabilities = [</div><div className="bn-2col" style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",marginTop:20}}>{c.services.map((s,i)=><a key={s} href={`/store/${slug}/catalog`} style={{border:"1px solid #ffffff12",padding:30,color:"#fff"}}><span style={{color:p.accent,fontFamily:"monospace"}}>0{i+1}</span><h3 style={{fontSize:24,margin:"10px 0"}}>{s}</h3><p style={{color:"#8c95a4"}}>Architecture, design and engineering with performance in mind.</p></a>)}</div><div style={{fontFamily:"monospace",color:p.accent,fontSize:11,marginTop:18}}>{"]"}</div></div></section><section style={{padding:"80px 5vw"}}><div style={{maxWidth:1300,margin:"auto"}}><small style={{color:p.accent}}>SELECTED BUILDS</small><div className="bn-grid-2" style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12,marginTop:25}}>{items.slice(0,6).map(card)}</div></div></section></main><Footer store={store} theme={{...theme,bg:p.bg,ink:p.ink,muted:"#8c95a4",border:"#ffffff14"}}/></div>;

 if(mode==="it-services") return <div style={{fontFamily:theme.font,background:p.bg,color:p.ink}}><Header store={store} slug={slug} theme={{...theme,ink:p.ink,bg:p.bg,accent:p.accent}} light label="Services"/><main><section style={{padding:"85px 5vw",background:"radial-gradient(circle at 80% 20%,#16466d 0,#07111f 45%)"}}><div style={{maxWidth:1300,margin:"auto"}}><small style={{color:p.accent,letterSpacing:".2em"}}>{c.eyebrow}</small><h1 style={{fontSize:"clamp(58px,8vw,115px)",lineHeight:.86,margin:"18px 0",maxWidth:1000}}>{c.headline}</h1><p style={{maxWidth:600,color:"#a8b7c8",lineHeight:1.8}}>{c.sub}</p><div style={{marginTop:28}}><CTA dark text="Talk to an engineer"/></div></div></section><section style={{padding:"60px 5vw"}}><div className="bn-grid-2" style={{maxWidth:1300,margin:"auto",display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:14}}>{["99.99%","24/7","< 15 min"].map((v,i)=><div key={v} style={{background:p.surface,padding:30,borderRadius:16}}><b style={{fontSize:42,color:p.accent}}>{v}</b><p style={{color:"#9aabbd"}}>{["Target uptime","Monitoring","Priority response"][i]}</p></div>)}</div></section><section style={{padding:"70px 5vw"}}><div style={{maxWidth:1300,margin:"auto"}}><h2 style={{fontSize:48}}>The operations layer.</h2><div style={{marginTop:25}}>{serviceList}</div></div></section><section style={{padding:"90px 5vw",background:p.accent,color:"#07111f",textAlign:"center"}}><h2 style={{fontSize:60}}>Make technology the quiet part of your business.</h2><div style={{marginTop:25}}><CTA text="Book an assessment"/></div></section></main><Footer store={store} theme={{...theme,bg:p.surface,ink:"#fff",muted:"#9aabbd",border:"#ffffff18"}}/></div>;

 if(mode==="architecture") return <div style={{fontFamily:theme.font,background:p.bg,color:p.ink}}><Header store={store} slug={slug} theme={{...theme,ink:p.ink,bg:p.bg,accent:p.accent}}/><main><section className="bn-2col" style={{padding:"0 5vw 100px",display:"grid",gridTemplateColumns:".65fr 1.35fr",minHeight:760}}><div style={{paddingTop:120}}><small style={{letterSpacing:".22em",color:p.accent}}>{c.eyebrow}</small><h1 style={{fontFamily:theme.headlineFont,fontSize:"clamp(58px,8vw,118px)",lineHeight:.82,margin:"20px 0"}}>{c.headline}</h1><p style={{maxWidth:470,lineHeight:1.8,color:muted}}>{c.sub}</p><div style={{marginTop:28}}><CTA text="Discuss a project"/></div></div><div style={{...img(hero,"linear-gradient(135deg,#b7aa96,#3f413d)"),marginTop:30,minHeight:620}}/></section><section style={{padding:"100px 5vw",background:p.surface,color:"#fff"}}><div className="bn-2col" style={{maxWidth:1300,margin:"auto",display:"grid",gridTemplateColumns:"1fr 1fr",gap:80}}><div><small style={{color:p.accent}}>THE PRACTICE</small><h2 style={{fontFamily:theme.headlineFont,fontSize:62}}>Proportion. Material. Light.</h2></div><div><p style={{color:"#ffffffaa",lineHeight:1.9}}>{c.sub}</p>{stats}</div></div></section><section style={{padding:"100px 5vw"}}><div style={{maxWidth:1300,margin:"auto"}}><small style={{color:p.accent}}>PROJECTS</small><div className="bn-2col" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:70,marginTop:30}}>{items.slice(0,4).map((x,i)=><a key={x.id} href={itemHref(slug,x)} style={{textDecoration:"none",color:"inherit",marginTop:i%2?80:0}}><div style={{aspectRatio:"1/1.15",...img(x.image,"#b6b0a5")}}/><h3 style={{fontFamily:theme.headlineFont,fontSize:25,margin:"13px 0 4px"}}>{x.name}</h3><small style={{color:muted}}>{x.categoryName||"Project"}</small></a>)}</div></div></section></main><Footer store={store} theme={{...theme,bg:p.surface,ink:"#fff",muted:"#b8b8b2",border:"#ffffff18"}}/></div>;

 // Engineering and construction share a technical visual language but have different information density.
 if(mode==="engineering") return <div style={{fontFamily:"Arial, sans-serif",background:p.bg,color:p.ink}}><Header store={store} slug={slug} theme={{...theme,ink:p.ink,bg:p.bg,accent:p.accent}}/><main><section style={{padding:"80px 5vw",background:p.surface,color:"#fff",backgroundImage:"linear-gradient(#ffffff08 1px,transparent 1px),linear-gradient(90deg,#ffffff08 1px,transparent 1px)",backgroundSize:"40px 40px"}}><div style={{maxWidth:1300,margin:"auto"}}><small style={{color:p.accent,fontWeight:900,letterSpacing:".2em"}}>{c.eyebrow}</small><h1 style={{fontSize:"clamp(58px,8vw,112px)",lineHeight:.85,margin:"20px 0",maxWidth:1050}}>{c.headline}</h1><p style={{maxWidth:620,color:"#b8c1c6",lineHeight:1.8}}>{c.sub}</p><div style={{marginTop:28}}><CTA dark text="Request a review"/></div></div></section><section style={{padding:"65px 5vw"}}><div style={{maxWidth:1300,margin:"auto"}}>{stats}</div></section><section style={{padding:"75px 5vw"}}><div style={{maxWidth:1300,margin:"auto"}}><div className="bn-2col" style={{display:"grid",gridTemplateColumns:".55fr 1.45fr",gap:50}}><div><small style={{color:p.accent}}>DISCIPLINES</small><h2 style={{fontSize:48}}>Technical confidence at every stage.</h2></div><div>{serviceList}</div></div></div></section><section style={{padding:"90px 5vw",background:"#d28a32",color:"#17232b"}}><div style={{maxWidth:900,margin:"auto",textAlign:"center"}}><h2 style={{fontSize:60}}>Complex project? Bring the drawings.</h2><div style={{marginTop:25}}><CTA text="Start an engineering project"/></div></div></section></main><Footer store={store} theme={{...theme,bg:p.surface,ink:"#fff",muted:"#b8c1c6",border:"#ffffff18"}}/></div>;

 return <div style={{fontFamily:theme.font,background:p.bg,color:p.ink}}><Header store={store} slug={slug} theme={{...theme,ink:p.ink,bg:p.bg,accent:p.accent}} light label="Projects"/><main><section style={{padding:"90px 5vw",background:p.surface,color:"#fff"}}><div className="bn-2col" style={{maxWidth:1350,margin:"auto",display:"grid",gridTemplateColumns:"1fr .65fr",gap:70,alignItems:"end"}}><div><small style={{color:p.accent,letterSpacing:".22em",fontWeight:900}}>{c.eyebrow}</small><h1 style={{fontSize:"clamp(62px,9vw,125px)",lineHeight:.83,letterSpacing:"-.06em",margin:"20px 0"}}>{c.headline}</h1><p style={{maxWidth:590,color:"#ffffffaa",lineHeight:1.8}}>{c.sub}</p><div style={{marginTop:28}}><CTA dark text={c.cta}/></div></div><div style={{padding:25,border:"1px solid #ffffff1f",background:"#ffffff08"}}><small>PROJECT BOARD</small><div style={{marginTop:18,display:"grid",gap:9}}>{["Site preparation","Structure","Finishes","Handover"].map((x,i)=><div key={x} style={{padding:"14px",border:"1px solid #ffffff14",display:"flex",justifyContent:"space-between"}}><span>{x}</span><span style={{color:p.accent}}>{["DONE","78%","42%","NEXT"][i]}</span></div>)}</div></div></div></section><section style={{padding:"70px 5vw"}}><div style={{maxWidth:1350,margin:"auto"}}><small style={{color:p.accent}}>CAPABILITIES</small><h2 style={{fontSize:50}}>From ground-breaking to handover.</h2><div style={{marginTop:30}}>{serviceList}</div></div></section><section style={{padding:"90px 5vw",background:p.bg}}><div style={{maxWidth:1350,margin:"auto"}}><div className="bn-2col" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:20}}>{items.slice(0,4).map(card)}</div></div></section><section style={{padding:"90px 5vw",background:p.accent,color:"#171817",textAlign:"center"}}><h2 style={{fontSize:62}}>Let's price the work properly.</h2><div style={{marginTop:25}}><CTA text="Request a quote"/></div></section></main><Footer store={store} theme={{...theme,bg:p.surface,ink:"#fff",muted:"#aaa",border:"#ffffff18"}}/></div>;
}

function Footer({store,theme}:{store:any;theme:any}){return <footer style={{padding:"28px 5vw",background:theme.bg,color:theme.muted||theme.ink,borderTop:`1px solid ${theme.border||`${theme.ink}18`}`,display:"flex",justifyContent:"space-between",gap:20,flexWrap:"wrap",fontSize:11}}><span>{store.name}</span><span>{store.contactEmail||store.contactPhone||""}</span><span>Powered by BizNest</span></footer>}
