import type { Capability } from "@/lib/capabilities";

export type ProfessionalServiceSubNiche = {
  id: string;
  name: string;
  group: "Creative & Design" | "Business Services" | "Technical Services" | "Construction & Technical";
  description: string;
  icon: string;
  capabilities: Capability[];
  services: string[];
  navigation: Array<{ label: string; href: string }>;
  primaryAction: string;
  journey: string[];
  emailThemes: string[];
  onboarding: { fields: Array<{ key: string; label: string; placeholder: string; type?: "text"|"number"|"textarea" }>; recommendations: string[] };
};

export const PROFESSIONAL_SERVICE_SUBNICHES: ProfessionalServiceSubNiche[] = [
  { id:"graphic-design", name:"Graphic Design & Printing", group:"Creative & Design", description:"A creative studio for branding, graphic design, printing and production work.", icon:"palette", capabilities:["services","portfolio","gallery","packages","reviews"], services:["Logo Design","Brand Identity","Flyer & Poster Design","Business Cards","Brochures & Packaging","Social Media Design","Large Format Printing","T-Shirt & Merchandise Printing","Signage & Banners","Stickers & Labels"], navigation:[{label:"Home",href:"/"},{label:"Services",href:"/services"},{label:"Portfolio",href:"/portfolio"},{label:"Start a Project",href:"/start-project"},{label:"About",href:"/about"},{label:"Contact",href:"/contact"}], primaryAction:"Start a project", journey:["Discover","Choose service","Request quote","Approve design","Production","Delivery / pickup"], emailThemes:["Design approval","Quote ready","Production started","Order ready","Portfolio showcase"], onboarding:{fields:[{key:"serviceFocus",label:"Creative services",placeholder:"e.g. branding, flyers, packaging, printing",type:"textarea"},{key:"printCapabilities",label:"Printing capabilities",placeholder:"e.g. digital, large format, apparel"},{key:"turnaround",label:"Typical turnaround",placeholder:"e.g. 2–5 business days"}],recommendations:["Upload 6–12 strong portfolio projects","Create clear design and print packages","Enable project quote requests","Show paper, finish and quantity options"]}},
  { id:"branding-agency", name:"Branding & Brand Identity", group:"Creative & Design", description:"A strategy-led branding studio built around identity systems, guidelines and brand launches.", icon:"sparkles", capabilities:["services","portfolio","packages","reviews"], services:["Brand Strategy","Logo & Identity","Visual Identity Systems","Brand Guidelines","Packaging Identity","Rebranding","Brand Launch Kits"], navigation:[{label:"Home",href:"/"},{label:"Services",href:"/services"},{label:"Case Studies",href:"/portfolio"},{label:"Start a Project",href:"/start-project"},{label:"About",href:"/about"},{label:"Contact",href:"/contact"}], primaryAction:"Start a branding project", journey:["Discover","Consultation","Proposal","Strategy","Identity design","Approval","Launch"], emailThemes:["Consultation confirmed","Proposal ready","Brand concept ready","Approval requested","Brand launch"], onboarding:{fields:[{key:"serviceFocus",label:"Branding capabilities",placeholder:"e.g. strategy, identity, packaging",type:"textarea"},{key:"clientType",label:"Ideal clients",placeholder:"e.g. startups, SMEs, hospitality"}],recommendations:["Show before/after case studies","Package brand identity tiers","Add a discovery-call CTA"]}},
  { id:"marketing-agency", name:"Marketing & Digital Agency", group:"Creative & Design", description:"A campaign and growth agency for strategy, content, advertising and digital marketing.", icon:"megaphone", capabilities:["services","portfolio","packages","bookings","reviews"], services:["Marketing Strategy","Social Media Management","Content Creation","Paid Advertising","SEO","Email Marketing","Campaign Management"], navigation:[{label:"Home",href:"/"},{label:"Services",href:"/services"},{label:"Case Studies",href:"/portfolio"},{label:"Book a Consultation",href:"/start-project"},{label:"About",href:"/about"},{label:"Contact",href:"/contact"}], primaryAction:"Book a consultation", journey:["Discover","Consultation","Audit","Proposal","Campaign","Reporting"], emailThemes:["Consultation reminder","Proposal ready","Campaign live","Monthly report","Campaign results"], onboarding:{fields:[{key:"serviceFocus",label:"Marketing capabilities",placeholder:"e.g. social, ads, SEO, content",type:"textarea"},{key:"clientType",label:"Ideal clients",placeholder:"e.g. restaurants, hotels, ecommerce"},{key:"teamSize",label:"Team size",placeholder:"e.g. 6",type:"number"}],recommendations:["Show measurable case studies","Create retainer packages","Add consultation booking"]}},
  { id:"photography-studio", name:"Photography & Visual Production", group:"Creative & Design", description:"A photography and visual production studio for commercial, portrait and event work.", icon:"camera", capabilities:["services","portfolio","gallery","packages","bookings","reviews"], services:["Portrait Photography","Wedding Photography","Product Photography","Corporate Photography","Event Coverage","Photo Editing","Video Production"], navigation:[{label:"Home",href:"/"},{label:"Services",href:"/services"},{label:"Portfolio",href:"/portfolio"},{label:"Book",href:"/start-project"},{label:"About",href:"/about"},{label:"Contact",href:"/contact"}], primaryAction:"Book a session", journey:["Discover","Choose package","Check availability","Book","Shoot","Delivery"], emailThemes:["Booking confirmation","Session reminder","Gallery ready","Review request","New package"], onboarding:{fields:[{key:"specialties",label:"Specialties",placeholder:"e.g. weddings, portraits, products"},{key:"packages",label:"Main packages",placeholder:"e.g. Mini, Standard, Premium"}],recommendations:["Create visual packages","Upload your strongest galleries","Set availability"]}},
  { id:"consulting", name:"Consulting & Advisory", group:"Business Services", description:"A professional advisory business focused on expertise, outcomes, consultations and proposals.", icon:"briefcase", capabilities:["services","packages","bookings","reviews"], services:["Business Consulting","Strategy Advisory","Operations Consulting","Growth Advisory","Training & Workshops","Retainer Advisory"], navigation:[{label:"Home",href:"/"},{label:"Expertise",href:"/services"},{label:"Case Studies",href:"/portfolio"},{label:"Book Consultation",href:"/start-project"},{label:"About",href:"/about"},{label:"Contact",href:"/contact"}], primaryAction:"Book a consultation", journey:["Discover","Consultation","Diagnosis","Proposal","Engagement","Review"], emailThemes:["Consultation booked","Proposal ready","Action plan","Progress update","Review request"], onboarding:{fields:[{key:"serviceFocus",label:"Advisory areas",placeholder:"e.g. strategy, operations, finance",type:"textarea"},{key:"clientType",label:"Who do you serve?",placeholder:"e.g. SMEs, founders, enterprises"}],recommendations:["Publish expertise and case studies","Offer consultation packages","Use a proposal/quote workflow"]}},
  { id:"accounting", name:"Accounting & Finance", group:"Business Services", description:"An accounting and finance practice for bookkeeping, tax, reporting and advisory services.", icon:"calculator", capabilities:["services","bookings","packages","reviews"], services:["Bookkeeping","Tax Preparation","Payroll","Financial Statements","CFO Advisory","Business Registration Support"], navigation:[{label:"Home",href:"/"},{label:"Services",href:"/services"},{label:"Resources",href:"/portfolio"},{label:"Book a Consultation",href:"/start-project"},{label:"About",href:"/about"},{label:"Contact",href:"/contact"}], primaryAction:"Book a consultation", journey:["Discover","Consultation","Document request","Proposal","Service","Delivery"], emailThemes:["Document request","Consultation booked","Report ready","Payment reminder","Tax deadline"], onboarding:{fields:[{key:"serviceFocus",label:"Finance services",placeholder:"e.g. bookkeeping, tax, payroll",type:"textarea"},{key:"clientType",label:"Client type",placeholder:"e.g. SMEs, individuals, startups"}],recommendations:["Explain credentials clearly","Create service packages","Provide secure document-request instructions"]}},
  { id:"legal", name:"Legal Services", group:"Business Services", description:"A professional legal practice for consultations, documentation and client matters.", icon:"scale", capabilities:["services","bookings","packages","reviews"], services:["Legal Consultation","Contract Review","Corporate Services","Property Law","Documentation","Compliance Advisory"], navigation:[{label:"Home",href:"/"},{label:"Practice Areas",href:"/services"},{label:"Insights",href:"/portfolio"},{label:"Request Consultation",href:"/start-project"},{label:"About",href:"/about"},{label:"Contact",href:"/contact"}], primaryAction:"Request a consultation", journey:["Discover","Conflict check","Consultation","Engagement","Matter updates","Completion"], emailThemes:["Consultation confirmation","Document request","Matter update","Invoice ready","Follow-up"], onboarding:{fields:[{key:"practiceAreas",label:"Practice areas",placeholder:"e.g. corporate, property, contracts",type:"textarea"},{key:"clientType",label:"Client type",placeholder:"e.g. individuals, SMEs, companies"}],recommendations:["Show practice areas","Add consultation booking","Make contact details prominent"]}},
  { id:"hr-recruitment", name:"HR & Recruitment", group:"Business Services", description:"A people and talent business for recruitment, HR advisory and workforce services.", icon:"users", capabilities:["services","bookings","packages","reviews"], services:["Recruitment","Executive Search","HR Consulting","Training","Outsourcing","Talent Assessment"], navigation:[{label:"Home",href:"/"},{label:"Services",href:"/services"},{label:"Success Stories",href:"/portfolio"},{label:"Start a Project",href:"/start-project"},{label:"About",href:"/about"},{label:"Contact",href:"/contact"}], primaryAction:"Start a hiring project", journey:["Discover","Brief","Candidate search","Shortlist","Interview","Placement"], emailThemes:["Hiring brief received","Candidate shortlist","Interview reminder","Placement update","Welcome"], onboarding:{fields:[{key:"serviceFocus",label:"HR capabilities",placeholder:"e.g. recruitment, payroll, training",type:"textarea"},{key:"clientType",label:"Ideal clients",placeholder:"e.g. startups, SMEs, enterprise"}],recommendations:["Create employer/candidate journeys","Show placement case studies","Add project enquiry"]}},
  { id:"web-development", name:"Web & Software Development", group:"Technical Services", description:"A product and engineering studio for websites, web apps, mobile apps and integrations.", icon:"code", capabilities:["services","portfolio","packages","bookings","reviews"], services:["Website Development","Web Applications","Mobile Apps","API Integrations","UI/UX Design","Maintenance & Support"], navigation:[{label:"Home",href:"/"},{label:"Services",href:"/services"},{label:"Case Studies",href:"/portfolio"},{label:"Start a Project",href:"/start-project"},{label:"About",href:"/about"},{label:"Contact",href:"/contact"}], primaryAction:"Start a project", journey:["Discover","Technical brief","Proposal","Design","Development","QA","Launch"], emailThemes:["Project brief received","Proposal ready","Milestone update","Approval requested","Launch complete"], onboarding:{fields:[{key:"serviceFocus",label:"Development capabilities",placeholder:"e.g. Next.js, mobile, APIs",type:"textarea"},{key:"clientType",label:"Ideal clients",placeholder:"e.g. startups, SMEs, enterprises"}],recommendations:["Show live case studies","Create project packages","Use milestone/project updates"]}},
  { id:"it-services", name:"IT & Technology Services", group:"Technical Services", description:"A technology services company for infrastructure, support, security and managed IT.", icon:"server", capabilities:["services","bookings","packages","reviews"], services:["IT Support","Cloud Services","Cybersecurity","Networking","Managed Services","Technology Audits"], navigation:[{label:"Home",href:"/"},{label:"Services",href:"/services"},{label:"Solutions",href:"/portfolio"},{label:"Request Support",href:"/start-project"},{label:"About",href:"/about"},{label:"Contact",href:"/contact"}], primaryAction:"Request a consultation", journey:["Discover","Assessment","Proposal","Implementation","Support","Review"], emailThemes:["Support request","Assessment ready","Maintenance notice","Service report","Renewal reminder"], onboarding:{fields:[{key:"serviceFocus",label:"IT capabilities",placeholder:"e.g. cloud, networking, cybersecurity",type:"textarea"},{key:"supportHours",label:"Support hours",placeholder:"e.g. Mon–Fri, 8am–6pm"}],recommendations:["Show service packages","Publish support SLAs","Add request-a-service CTA"]}},
  { id:"architecture", name:"Architecture & Interior Design", group:"Construction & Technical", description:"A design practice for architecture, interiors, space planning and visualisation.", icon:"ruler", capabilities:["services","portfolio","gallery","packages","bookings","reviews"], services:["Architecture","Interior Design","Space Planning","3D Visualisation","Renovation Design","Project Supervision"], navigation:[{label:"Home",href:"/"},{label:"Services",href:"/services"},{label:"Projects",href:"/portfolio"},{label:"Start a Project",href:"/start-project"},{label:"About",href:"/about"},{label:"Contact",href:"/contact"}], primaryAction:"Discuss your project", journey:["Discover","Site / brief","Concept","Proposal","Design","Approval","Delivery"], emailThemes:["Consultation booked","Concept ready","Drawing approval","Project update","Project completion"], onboarding:{fields:[{key:"projectTypes",label:"Project types",placeholder:"e.g. residential, commercial, hospitality"},{key:"serviceArea",label:"Service area",placeholder:"e.g. Abuja, Lagos"}],recommendations:["Show project case studies","Create design packages","Collect project briefs"]}},
  { id:"engineering", name:"Engineering Services", group:"Construction & Technical", description:"An engineering practice for technical design, consulting, inspections and project support.", icon:"settings", capabilities:["services","portfolio","packages","bookings","reviews"], services:["Engineering Design","Consulting","Site Inspection","Project Management","Technical Reports","Maintenance Planning"], navigation:[{label:"Home",href:"/"},{label:"Services",href:"/services"},{label:"Projects",href:"/portfolio"},{label:"Request a Quote",href:"/start-project"},{label:"About",href:"/about"},{label:"Contact",href:"/contact"}], primaryAction:"Request a quote", journey:["Discover","Site assessment","Scope","Quote","Engineering","Delivery"], emailThemes:["Site visit booked","Quote ready","Technical approval","Progress report","Project completion"], onboarding:{fields:[{key:"engineeringAreas",label:"Engineering areas",placeholder:"e.g. civil, electrical, mechanical",type:"textarea"},{key:"serviceArea",label:"Service area",placeholder:"e.g. Abuja and nearby states"}],recommendations:["Show completed projects","Explain qualifications","Use quote requests for custom work"]}},
  { id:"construction-company", name:"Construction & Building", group:"Construction & Technical", description:"A construction company for residential, commercial, renovation and maintenance projects.", icon:"hard-hat", capabilities:["services","portfolio","gallery","packages","reviews"], services:["New Builds","Renovation","Remodelling","Fit-Outs","Maintenance","Project Management"], navigation:[{label:"Home",href:"/"},{label:"Services",href:"/services"},{label:"Projects",href:"/portfolio"},{label:"Request a Site Visit",href:"/start-project"},{label:"About",href:"/about"},{label:"Contact",href:"/contact"}], primaryAction:"Request a site visit", journey:["Discover","Site visit","Scope","Quote","Build","Handover"], emailThemes:["Site visit confirmation","Quote ready","Project update","Milestone complete","Handover"], onboarding:{fields:[{key:"projectTypes",label:"Project types",placeholder:"e.g. residential, commercial, renovation"},{key:"serviceArea",label:"Service area",placeholder:"e.g. Abuja, Nasarawa"},{key:"quoteProcess",label:"Quotation process",placeholder:"e.g. site inspection before quotation",type:"textarea"}],recommendations:["Show completed projects","Add a site-visit CTA","Explain your build process"]}},
];

export const PROFESSIONAL_SERVICE_GROUPS = ["Creative & Design","Business Services","Technical Services","Construction & Technical"] as const;
export function getProfessionalServiceSubNiche(id?: string|null) { return PROFESSIONAL_SERVICE_SUBNICHES.find((n)=>n.id===id) ?? PROFESSIONAL_SERVICE_SUBNICHES[0]; }
export function getProfessionalServiceSubNicheByName(name?: string|null) { return PROFESSIONAL_SERVICE_SUBNICHES.find((n)=>n.name===name) ?? null; }
export function professionalServiceSubNicheNames() { return PROFESSIONAL_SERVICE_SUBNICHES.map((n)=>n.name); }
