"use server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";
import { seedSampleListings } from "@/lib/actions/store";
import { GRANDEUR_TEMPLATE_NAME, GRANDEUR_THEME } from "@/lib/template-themes";
import { HOTEL_TEMPLATE_NAME, HOTEL_THEME, TASTEHOUSE_TEMPLATE_NAME, TASTEHOUSE_THEME, EXAMPLE_TEMPLATE_NAME, EXAMPLE_THEME } from "@/lib/template-themes";
import type { Prisma } from "@prisma/client";
import type { ActionResult } from "@/types/actions";
export async function setStoreTemplate(slug:string,templateId:string):Promise<ActionResult>{
 const session=await auth(); if(!session?.user?.id)return {success:false,error:"You must be signed in."};
 const store=await prisma.store.findUnique({where:{slug},include:{business:true,subscription:true}}); if(!store)return {success:false,error:"Store not found."};
 if(store.business.userId!==session.user.id)return {success:false,error:"You don't have access to this store."};
 let template=await prisma.storeTemplate.findUnique({where:{id:templateId}});
 if(!template && templateId===`__grandeur__:${GRANDEUR_TEMPLATE_NAME}`) template=await prisma.storeTemplate.upsert({where:{name:GRANDEUR_TEMPLATE_NAME},update:{isActive:true,category:"Restaurant",tierRank:GRANDEUR_THEME.tierRank,config:GRANDEUR_THEME as unknown as Prisma.InputJsonValue},create:{name:GRANDEUR_TEMPLATE_NAME,category:"Restaurant",tierRank:GRANDEUR_THEME.tierRank,isActive:true,config:GRANDEUR_THEME as unknown as Prisma.InputJsonValue}});
 if(!template && templateId===`__theluso__:${HOTEL_TEMPLATE_NAME}`) template=await prisma.storeTemplate.upsert({where:{name:HOTEL_TEMPLATE_NAME},update:{isActive:true,category:"Hotel",tierRank:HOTEL_THEME.tierRank,config:HOTEL_THEME as unknown as Prisma.InputJsonValue},create:{name:HOTEL_TEMPLATE_NAME,category:"Hotel",tierRank:HOTEL_THEME.tierRank,isActive:true,config:HOTEL_THEME as unknown as Prisma.InputJsonValue}});
 if(!template && templateId===`__example__:${EXAMPLE_TEMPLATE_NAME}`) template=await prisma.storeTemplate.upsert({where:{name:EXAMPLE_TEMPLATE_NAME},update:{isActive:true,category:"Electronics & Retail",tierRank:EXAMPLE_THEME.tierRank,config:EXAMPLE_THEME as unknown as Prisma.InputJsonValue},create:{name:EXAMPLE_TEMPLATE_NAME,category:"Electronics & Retail",tierRank:EXAMPLE_THEME.tierRank,isActive:true,config:EXAMPLE_THEME as unknown as Prisma.InputJsonValue}});
 if(!template && templateId===`__tastehouse__:${TASTEHOUSE_TEMPLATE_NAME}`) template=await prisma.storeTemplate.upsert({where:{name:TASTEHOUSE_TEMPLATE_NAME},update:{isActive:true,category:"Restaurant",tierRank:TASTEHOUSE_THEME.tierRank,config:TASTEHOUSE_THEME as unknown as Prisma.InputJsonValue},create:{name:TASTEHOUSE_TEMPLATE_NAME,category:"Restaurant",tierRank:TASTEHOUSE_THEME.tierRank,isActive:true,config:TASTEHOUSE_THEME as unknown as Prisma.InputJsonValue}});
 if(!template)return {success:false,error:"Template not found."};
 const allowed=template.name===GRANDEUR_TEMPLATE_NAME||template.name===HOTEL_TEMPLATE_NAME||template.name===TASTEHOUSE_TEMPLATE_NAME||template.name===EXAMPLE_TEMPLATE_NAME;
 if(!allowed)return {success:false,error:"That template has been retired."};
 const category=String(store.businessType||store.business.category||"").toLowerCase();
 const compatible=template.name===HOTEL_TEMPLATE_NAME ? (category.includes("hotel")||category.includes("lodging")) : template.name===EXAMPLE_TEMPLATE_NAME ? (category.includes("retail")||category.includes("electronics")||category.includes("commerce")||category.includes("shop")) : (category.includes("restaurant")||category.includes("food"));
 if(!compatible)return {success:false,error:`${template.name} is not compatible with this business.`};
 const features=store.subscription?.features as {templateTier?:number}|null; const planRank=features?.templateTier??1;
 if(template.tierRank>planRank)return {success:false,error:"This template requires a higher plan."};
 await prisma.store.update({where:{id:store.id},data:{templateId:template.id}});
 if(template.name===GRANDEUR_TEMPLATE_NAME)await seedSampleListings(slug);
 revalidatePath(`/store/${slug}`);revalidatePath(`/store/${slug}/admin/templates`);revalidatePath(`/store/${slug}/admin/customize`);return {success:true,data:undefined};
}