"use server";
import { prisma } from "@/lib/prisma";
import { assertStorePermission } from "@/lib/access/assert-store-access";

export async function createRealEstateProperty(slug:string,input:{name:string;propertyType:string;address?:string}){const a=await assertStorePermission(slug,"products");if(!a.success)return a;return {success:true,data:await prisma.realEstateProperty.create({data:{storeId:a.store.id,name:input.name.trim(),propertyType:input.propertyType,address:input.address?.trim()||null}})}}
export async function createRealEstateUnit(slug:string,input:{propertyId:string;unitNo:string;rentAmount?:number}){const a=await assertStorePermission(slug,"products");if(!a.success)return a;const p=await prisma.realEstateProperty.findFirst({where:{id:input.propertyId,storeId:a.store.id}});if(!p)return {success:false,error:"Property not found."};return {success:true,data:await prisma.realEstateUnit.create({data:{propertyId:p.id,unitNo:input.unitNo.trim(),rentAmount:input.rentAmount}})}}
export async function createVehicle(slug:string,input:{registration:string;make?:string;model?:string;year?:number;customerName?:string;customerPhone?:string;mileage?:number}){const a=await assertStorePermission(slug,"products");if(!a.success)return a;return {success:true,data:await prisma.autoVehicle.create({data:{storeId:a.store.id,...input,registration:input.registration.trim().toUpperCase()}})}}
export async function createPhotoShoot(slug:string,input:{title:string;shootDate?:Date;clientName?:string;clientEmail?:string}){const a=await assertStorePermission(slug,"products");if(!a.success)return a;return {success:true,data:await prisma.photoShoot.create({data:{storeId:a.store.id,...input,title:input.title.trim()}})}}
export async function createTailoringJob(slug:string,input:{jobNo:string;customerName:string;garmentType:string;dueDate?:Date;measurements?:unknown;fabric?:unknown}){const a=await assertStorePermission(slug,"products");if(!a.success)return a;return {success:true,data:await prisma.tailoringJob.create({data:{storeId:a.store.id,jobNo:input.jobNo.trim(),customerName:input.customerName.trim(),garmentType:input.garmentType.trim(),dueDate:input.dueDate,measurements:input.measurements as any,fabric:input.fabric as any}})}}
