-- Root-cause fix for the app's "increasingly slow" symptom.
--
-- prisma/migrations never contains a CREATE TABLE for User, Business, Store,
-- Product, Order, Payment, and ~35 other core models (verified: no
-- `CREATE TABLE "X"` for any of them anywhere in this folder). Those tables
-- were created directly against the live Supabase DB at some point (db push,
-- or a manual baseline), outside of migration history. That means every
-- @@index / @@unique / @unique this schema declares for those models is only
-- a promise on paper -- there is no guarantee the actual index exists in the
-- live database.
--
-- With a handful of rows, a missing index on e.g. Order.storeId or
-- Product.storeId costs nothing: Postgres just seq-scans a tiny table. As
-- orders/products/visits accumulate, those exact same lookups go from
-- instant to multi-second -- which is precisely a "getting worse over time"
-- curve, not a code bug. This migration is the fix.
--
-- Every statement below is IF NOT EXISTS: for any table where the index
-- genuinely was missing, it gets created; for any table already correctly
-- migrated, this is a safe no-op. Idempotent and re-runnable.
--
-- Auto-generated by parsing prisma/schema.prisma's @@index/@@unique/@unique
-- directives and reproducing Prisma's default naming convention
-- ("<Model>_<field(s)>_idx" / "_key"), verified against existing migration
-- files (e.g. PurchaseOrder_storeId_idx already matches this exact pattern).

CREATE INDEX IF NOT EXISTS "User_role_idx" ON "User"("role");
CREATE UNIQUE INDEX IF NOT EXISTS "User_email_customerScopeStoreId_key" ON "User"("email", "customerScopeStoreId");
CREATE INDEX IF NOT EXISTS "StoreCustomerAddress_storeId_userId_idx" ON "StoreCustomerAddress"("storeId", "userId");
CREATE INDEX IF NOT EXISTS "StoreCustomerAddress_storeId_userId_isDefault_idx" ON "StoreCustomerAddress"("storeId", "userId", "isDefault");
CREATE UNIQUE INDEX IF NOT EXISTS "StoreLoyaltyAccount_storeId_userId_key" ON "StoreLoyaltyAccount"("storeId", "userId");
CREATE INDEX IF NOT EXISTS "StoreLoyaltyAccount_storeId_idx" ON "StoreLoyaltyAccount"("storeId");
CREATE INDEX IF NOT EXISTS "StoreLoyaltyEntry_loyaltyAccountId_createdAt_idx" ON "StoreLoyaltyEntry"("loyaltyAccountId", "createdAt");
CREATE INDEX IF NOT EXISTS "StoreLoyaltyEntry_orderId_type_idx" ON "StoreLoyaltyEntry"("orderId", "type");
CREATE INDEX IF NOT EXISTS "Address_userId_idx" ON "Address"("userId");
CREATE UNIQUE INDEX IF NOT EXISTS "WishlistItem_userId_productId_serviceId_key" ON "WishlistItem"("userId", "productId", "serviceId");
CREATE INDEX IF NOT EXISTS "WishlistItem_userId_idx" ON "WishlistItem"("userId");
CREATE INDEX IF NOT EXISTS "RecentlyViewed_userId_viewedAt_idx" ON "RecentlyViewed"("userId", "viewedAt");
CREATE UNIQUE INDEX IF NOT EXISTS "FavoriteBusiness_userId_businessId_key" ON "FavoriteBusiness"("userId", "businessId");
CREATE UNIQUE INDEX IF NOT EXISTS "SavedCart_userId_storeId_key" ON "SavedCart"("userId", "storeId");
CREATE INDEX IF NOT EXISTS "StoreCustomerProfile_storeId_createdAt_idx" ON "StoreCustomerProfile"("storeId", "createdAt");
CREATE INDEX IF NOT EXISTS "StoreCustomerProfile_storeId_phone_idx" ON "StoreCustomerProfile"("storeId", "phone");
CREATE INDEX IF NOT EXISTS "StoreCustomerProfile_storeId_email_idx" ON "StoreCustomerProfile"("storeId", "email");
CREATE INDEX IF NOT EXISTS "StoreCustomerProfile_userId_idx" ON "StoreCustomerProfile"("userId");
CREATE UNIQUE INDEX IF NOT EXISTS "StoreCustomer_userId_storeId_key" ON "StoreCustomer"("userId", "storeId");
CREATE INDEX IF NOT EXISTS "StoreCustomer_storeId_idx" ON "StoreCustomer"("storeId");
CREATE UNIQUE INDEX IF NOT EXISTS "Account_provider_providerAccountId_key" ON "Account"("provider", "providerAccountId");
CREATE UNIQUE INDEX IF NOT EXISTS "Session_sessionToken_key" ON "Session"("sessionToken");
CREATE UNIQUE INDEX IF NOT EXISTS "VerificationToken_token_key" ON "VerificationToken"("token");
CREATE UNIQUE INDEX IF NOT EXISTS "VerificationToken_identifier_token_key" ON "VerificationToken"("identifier", "token");
CREATE UNIQUE INDEX IF NOT EXISTS "Business_userId_key" ON "Business"("userId");
CREATE INDEX IF NOT EXISTS "Business_verificationStatus_idx" ON "Business"("verificationStatus");
CREATE INDEX IF NOT EXISTS "Business_category_idx" ON "Business"("category");
CREATE INDEX IF NOT EXISTS "Business_city_state_idx" ON "Business"("city", "state");
CREATE INDEX IF NOT EXISTS "Business_latitude_longitude_idx" ON "Business"("latitude", "longitude");
CREATE INDEX IF NOT EXISTS "Business_trustScore_idx" ON "Business"("trustScore");
CREATE UNIQUE INDEX IF NOT EXISTS "Store_businessId_key" ON "Store"("businessId");
CREATE UNIQUE INDEX IF NOT EXISTS "Store_slug_key" ON "Store"("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "Store_customDomain_key" ON "Store"("customDomain");
CREATE INDEX IF NOT EXISTS "Store_status_idx" ON "Store"("status");
CREATE UNIQUE INDEX IF NOT EXISTS "StoreStaff_inviteToken_key" ON "StoreStaff"("inviteToken");
CREATE UNIQUE INDEX IF NOT EXISTS "StoreStaff_storeId_invitedEmail_key" ON "StoreStaff"("storeId", "invitedEmail");
CREATE UNIQUE INDEX IF NOT EXISTS "StoreStaff_storeId_username_key" ON "StoreStaff"("storeId", "username");
CREATE INDEX IF NOT EXISTS "StoreStaff_userId_idx" ON "StoreStaff"("userId");
CREATE INDEX IF NOT EXISTS "StoreStaff_inviteToken_idx" ON "StoreStaff"("inviteToken");
CREATE INDEX IF NOT EXISTS "StoreActivityLog_storeId_createdAt_idx" ON "StoreActivityLog"("storeId", "createdAt");
CREATE UNIQUE INDEX IF NOT EXISTS "StoreTemplate_name_key" ON "StoreTemplate"("name");
CREATE UNIQUE INDEX IF NOT EXISTS "StorePage_storeId_slug_key" ON "StorePage"("storeId", "slug");
CREATE UNIQUE INDEX IF NOT EXISTS "Category_name_key" ON "Category"("name");
CREATE INDEX IF NOT EXISTS "SearchQuery_category_city_idx" ON "SearchQuery"("category", "city");
CREATE INDEX IF NOT EXISTS "SearchQuery_createdAt_idx" ON "SearchQuery"("createdAt");
CREATE UNIQUE INDEX IF NOT EXISTS "Product_storeId_slug_key" ON "Product"("storeId", "slug");
CREATE INDEX IF NOT EXISTS "Product_storeId_idx" ON "Product"("storeId");
CREATE UNIQUE INDEX IF NOT EXISTS "ProductVariant_storeId_sku_key" ON "ProductVariant"("storeId", "sku");
CREATE UNIQUE INDEX IF NOT EXISTS "ProductVariant_storeId_barcode_key" ON "ProductVariant"("storeId", "barcode");
CREATE INDEX IF NOT EXISTS "ProductVariant_productId_idx" ON "ProductVariant"("productId");
CREATE INDEX IF NOT EXISTS "ProductVariant_storeId_idx" ON "ProductVariant"("storeId");
CREATE UNIQUE INDEX IF NOT EXISTS "Service_storeId_slug_key" ON "Service"("storeId", "slug");
CREATE INDEX IF NOT EXISTS "Service_storeId_idx" ON "Service"("storeId");
CREATE UNIQUE INDEX IF NOT EXISTS "InventoryItem_productId_key" ON "InventoryItem"("productId");
CREATE UNIQUE INDEX IF NOT EXISTS "InventoryItem_storeId_sku_key" ON "InventoryItem"("storeId", "sku");
CREATE UNIQUE INDEX IF NOT EXISTS "InventoryItem_storeId_barcode_key" ON "InventoryItem"("storeId", "barcode");
CREATE INDEX IF NOT EXISTS "StockMovement_inventoryItemId_createdAt_idx" ON "StockMovement"("inventoryItemId", "createdAt");
CREATE INDEX IF NOT EXISTS "StockMovement_variantId_createdAt_idx" ON "StockMovement"("variantId", "createdAt");
CREATE INDEX IF NOT EXISTS "StockMovement_storeId_idx" ON "StockMovement"("storeId");
CREATE INDEX IF NOT EXISTS "Booking_serviceId_scheduledAt_idx" ON "Booking"("serviceId", "scheduledAt");
CREATE INDEX IF NOT EXISTS "Booking_storeId_idx" ON "Booking"("storeId");
CREATE INDEX IF NOT EXISTS "PosCommissionSettlement_storeId_createdAt_idx" ON "PosCommissionSettlement"("storeId", "createdAt");
CREATE INDEX IF NOT EXISTS "AbandonedCheckoutNotification_orderId_idx" ON "AbandonedCheckoutNotification"("orderId");
CREATE INDEX IF NOT EXISTS "WebhookEndpoint_storeId_idx" ON "WebhookEndpoint"("storeId");
CREATE INDEX IF NOT EXISTS "WebhookDelivery_endpointId_idx" ON "WebhookDelivery"("endpointId");
CREATE INDEX IF NOT EXISTS "WebhookDelivery_status_nextAttemptAt_idx" ON "WebhookDelivery"("status", "nextAttemptAt");
CREATE UNIQUE INDEX IF NOT EXISTS "Order_idempotencyKey_key" ON "Order"("idempotencyKey");
CREATE INDEX IF NOT EXISTS "Order_storeId_idx" ON "Order"("storeId");
CREATE INDEX IF NOT EXISTS "Order_buyerId_idx" ON "Order"("buyerId");
CREATE INDEX IF NOT EXISTS "Order_customerProfileId_idx" ON "Order"("customerProfileId");
CREATE INDEX IF NOT EXISTS "OrderStatusEvent_orderId_createdAt_idx" ON "OrderStatusEvent"("orderId", "createdAt");
CREATE UNIQUE INDEX IF NOT EXISTS "Payment_reference_key" ON "Payment"("reference");
CREATE UNIQUE INDEX IF NOT EXISTS "Payment_refundReference_key" ON "Payment"("refundReference");
CREATE INDEX IF NOT EXISTS "Payment_orderId_idx" ON "Payment"("orderId");
CREATE INDEX IF NOT EXISTS "Payment_storeId_idx" ON "Payment"("storeId");
CREATE INDEX IF NOT EXISTS "Payment_status_idx" ON "Payment"("status");
CREATE UNIQUE INDEX IF NOT EXISTS "Dispute_orderId_key" ON "Dispute"("orderId");
CREATE INDEX IF NOT EXISTS "Dispute_status_idx" ON "Dispute"("status");
CREATE INDEX IF NOT EXISTS "DisputeEvidence_disputeId_idx" ON "DisputeEvidence"("disputeId");
CREATE INDEX IF NOT EXISTS "StoreVisit_storeId_createdAt_idx" ON "StoreVisit"("storeId", "createdAt");
CREATE INDEX IF NOT EXISTS "DeliveryZone_storeId_idx" ON "DeliveryZone"("storeId");
CREATE INDEX IF NOT EXISTS "DeliveryZone_storeId_city_idx" ON "DeliveryZone"("storeId", "city");
CREATE UNIQUE INDEX IF NOT EXISTS "NewsletterSubscriber_storeId_email_key" ON "NewsletterSubscriber"("storeId", "email");
CREATE INDEX IF NOT EXISTS "NewsletterSubscriber_storeId_idx" ON "NewsletterSubscriber"("storeId");
CREATE UNIQUE INDEX IF NOT EXISTS "Coupon_storeId_code_key" ON "Coupon"("storeId", "code");
CREATE UNIQUE INDEX IF NOT EXISTS "ReviewResponse_reviewId_key" ON "ReviewResponse"("reviewId");
CREATE UNIQUE INDEX IF NOT EXISTS "Conversation_orderId_key" ON "Conversation"("orderId");
CREATE UNIQUE INDEX IF NOT EXISTS "ConversationParticipant_conversationId_userId_key" ON "ConversationParticipant"("conversationId", "userId");
CREATE INDEX IF NOT EXISTS "Notification_userId_readAt_idx" ON "Notification"("userId", "readAt");
CREATE UNIQUE INDEX IF NOT EXISTS "PushSubscription_endpoint_key" ON "PushSubscription"("endpoint");
CREATE INDEX IF NOT EXISTS "PushSubscription_userId_idx" ON "PushSubscription"("userId");
CREATE UNIQUE INDEX IF NOT EXISTS "Subscription_name_key" ON "Subscription"("name");
CREATE INDEX IF NOT EXISTS "AuditLog_entity_entityId_idx" ON "AuditLog"("entity", "entityId");
CREATE INDEX IF NOT EXISTS "SystemEvent_category_createdAt_idx" ON "SystemEvent"("category", "createdAt");
CREATE INDEX IF NOT EXISTS "SystemEvent_level_createdAt_idx" ON "SystemEvent"("level", "createdAt");
CREATE UNIQUE INDEX IF NOT EXISTS "PlatformSetting_key_key" ON "PlatformSetting"("key");
CREATE UNIQUE INDEX IF NOT EXISTS "LoyaltyAccount_userId_key" ON "LoyaltyAccount"("userId");
CREATE INDEX IF NOT EXISTS "LoyaltyEntry_loyaltyAccountId_idx" ON "LoyaltyEntry"("loyaltyAccountId");
CREATE UNIQUE INDEX IF NOT EXISTS "Invoice_invoiceNo_key" ON "Invoice"("invoiceNo");
CREATE UNIQUE INDEX IF NOT EXISTS "Invoice_orderId_key" ON "Invoice"("orderId");
CREATE UNIQUE INDEX IF NOT EXISTS "Invoice_paymentId_key" ON "Invoice"("paymentId");
CREATE INDEX IF NOT EXISTS "Invoice_storeId_idx" ON "Invoice"("storeId");
CREATE INDEX IF NOT EXISTS "Invoice_customerId_idx" ON "Invoice"("customerId");
CREATE UNIQUE INDEX IF NOT EXISTS "Quote_quoteNo_key" ON "Quote"("quoteNo");
CREATE UNIQUE INDEX IF NOT EXISTS "Quote_depositPaymentId_key" ON "Quote"("depositPaymentId");
CREATE UNIQUE INDEX IF NOT EXISTS "Quote_orderId_key" ON "Quote"("orderId");
CREATE INDEX IF NOT EXISTS "Quote_storeId_idx" ON "Quote"("storeId");
CREATE INDEX IF NOT EXISTS "Quote_customerId_idx" ON "Quote"("customerId");
CREATE INDEX IF NOT EXISTS "Supplier_storeId_idx" ON "Supplier"("storeId");
CREATE UNIQUE INDEX IF NOT EXISTS "SupplierProduct_supplierId_productId_key" ON "SupplierProduct"("supplierId", "productId");
CREATE INDEX IF NOT EXISTS "SupplierProduct_productId_idx" ON "SupplierProduct"("productId");
CREATE UNIQUE INDEX IF NOT EXISTS "PurchaseOrder_poNumber_key" ON "PurchaseOrder"("poNumber");
CREATE INDEX IF NOT EXISTS "PurchaseOrder_storeId_idx" ON "PurchaseOrder"("storeId");
CREATE INDEX IF NOT EXISTS "PurchaseOrder_supplierId_idx" ON "PurchaseOrder"("supplierId");
CREATE INDEX IF NOT EXISTS "PurchaseOrderItem_purchaseOrderId_idx" ON "PurchaseOrderItem"("purchaseOrderId");
CREATE INDEX IF NOT EXISTS "PurchaseOrderItem_productId_idx" ON "PurchaseOrderItem"("productId");
CREATE INDEX IF NOT EXISTS "PurchaseOrderItem_variantId_idx" ON "PurchaseOrderItem"("variantId");

-- total statements: 117
