import React from "react";
import Link from "next/link";
import { HeenzyStorefront } from "@/components/storefront/templates/heenzy-home";
import type { CategoryTreeNode } from "@/lib/storefront-categories";

export type LegacyCatalogItem = {
  id:string; kind:"product"|"service"; name:string; description:string|null; price:number;
  currency:string; image:string|null; categoryName:string|null; type:string; rentalUnit:string|null; isBookable:boolean;
};
type Review={id:string;rating:number;comment:string|null;author:{name:string|null}};
type Store={name:string;logoUrl:string|null;bannerUrl:string|null;contactEmail:string|null;contactPhone:string|null;sellsProducts:boolean;heroOverrides?:any;storyOverrides?:any;socialLinks?:any;business:{description:string|null;phone?:string|null;email?:string|null;city?:string|null;state?:string|null;country?:string|null}};
type Props={store:Store;slug:string;catalogItems:LegacyCatalogItem[];navCategories:CategoryTreeNode[];goodReviews:Review[];avgRating:number|null;completedOrders:number;trustScore?:number|null;trustChecklist?:any;social?:Record<string,string>;theme?:any};

const href=(slug:string,p="")=>`/store/${slug}${p}`;
const heroHeadline=(st:Store)=>String(st.heroOverrides?.headline||"").trim()||null;
const heroSub=(st:Store,fallback:string)=>String(st.heroOverrides?.subtitle||"").trim()||st.business.description||fallback;
const money=(i:LegacyCatalogItem)=>`${i.currency} ${i.price.toLocaleString()}`;
const image=(url:string|null)=>url?{backgroundImage:`linear-gradient(135deg,rgba(0,0,0,.04),rgba(0,0,0,.08)),url(${url})`}:undefined;

function Header({p,variant}:{p:Props;variant:string}){
 const {store,slug}=p;
 return <header className={`lt-header lt-header-${variant}`}><Link href={href(slug)} className="lt-brand">{store.logoUrl?<img src={store.logoUrl} alt={store.name}/>:<span>{store.name?.[0]||"B"}</span>}<b>{store.name}</b></Link><nav><Link href={href(slug)}>Home</Link><Link href={href(slug,"/catalog")}>Catalog</Link><Link href={href(slug,"/search")}>Search</Link><Link href={href(slug,"/about")}>About</Link></nav><div className="lt-actions"><Link href={href(slug,"/account")}>Account</Link>{store.sellsProducts&&<Link href={href(slug,"/cart")}>Cart</Link>}</div></header>;
}
function Cards({p,items,limit=8,className=""}:{p:Props;items:LegacyCatalogItem[];limit?:number;className?:string}){
 return <div className={`lt-cards ${className}`}>{items.slice(0,limit).map(i=><Link href={href(p.slug,`/${i.kind}/${i.id}`)} className="lt-card" key={i.id}><div className="lt-card-image" style={image(i.image)}>{!i.image&&<span>{i.name?.[0]}</span>}</div><div className="lt-card-body"><small>{i.categoryName||i.kind}</small><h3>{i.name}</h3><p>{i.description||"Quality products and services from this business."}</p><strong>{money(i)}</strong><em>{i.isBookable?"Book now →":"View details →"}</em></div></Link>)}</div>;
}
function Footer({p,dark=false}:{p:Props;dark?:boolean}){const st=p.store;const phone=st.contactPhone||st.business.phone;const email=st.contactEmail||st.business.email;const address=[st.business.city,st.business.state,st.business.country].filter(Boolean).join(", ");const social=(st.socialLinks||{}) as Record<string,string>;return <footer className={`lt-footer ${dark?"dark":""}`}><div><b>{st.name}</b><p>{st.business.description||"Built with BizNest."}</p></div><div><b>Explore</b><Link href={href(p.slug,"/catalog")}>Catalog</Link><Link href={href(p.slug,"/search")}>Search</Link><Link href={href(p.slug,"/account")}>Account</Link></div><div><b>Contact</b>{phone&&<a href={`tel:${phone}`}>{phone}</a>}{email&&<a href={`mailto:${email}`}>{email}</a>}{address&&<span>{address}</span>}{Object.entries(social).filter(([,v])=>v).map(([k,v])=><a key={k} href={String(v)} target="_blank" rel="noopener noreferrer" style={{textTransform:"capitalize"}}>{k}</a>)}</div></footer>}

function Fresh({p}:{p:Props}){
 const {store,slug,catalogItems}=p; const hero=store.bannerUrl||catalogItems[0]?.image;
 return <div className="lt-root fresh"><Header p={p} variant="fresh"/><section className="fresh-hero" style={image(hero)}><div><small>{store.name.toUpperCase()}</small><h1>{heroHeadline(store)||<>Better products.<br/><em>Better everyday.</em></>}</h1><p>{heroSub(store,"Fresh essentials and thoughtful service, presented simply.")}</p><Link href={href(slug,"/catalog")} className="lt-btn">Explore the collection →</Link></div></section><section className="fresh-cats"><h2>Shop by category</h2><div>{p.navCategories.slice(0,6).map(c=><Link href={href(slug,`/category/${c.id}`)} key={c.id}>{c.name}<span>→</span></Link>)}</div></section><section className="lt-section"><div className="lt-section-head"><div><small>CURATED FOR YOU</small><h2>Fresh picks</h2></div><Link href={href(slug,"/catalog")}>View all →</Link></div><Cards p={p} items={catalogItems}/></section><section className="fresh-story"><div><small>ABOUT THE STORE</small><h2>Simple, useful and made for real life.</h2><p>{store.business.description||"Discover a cleaner way to shop and book."}</p></div><div className="fresh-stat"><b>{catalogItems.length}+</b><span>items & services</span><b>{p.completedOrders}+</b><span>completed orders</span></div></section><Footer p={p}/></div>
}
function Nova({p}:{p:Props}){
 const {store,slug,catalogItems}=p; const hero=store.bannerUrl||catalogItems[0]?.image;
 return <div className="lt-root nova"><aside className="nova-side"><Link href={href(slug)} className="nova-mark">{store.logoUrl?<img src={store.logoUrl} alt=""/>:<span>{store.name?.[0]?.toUpperCase()||"N"}</span>}</Link><div><small>STUDIO</small><h4>{store.name}</h4><nav><Link href={href(slug)}>Home</Link><Link href={href(slug,"/catalog")}>Work / Catalog</Link><Link href={href(slug,"/about")}>About</Link><Link href={href(slug,"/search")}>Contact</Link></nav></div><small>© {new Date().getFullYear()}</small></aside><main className="nova-main"><section className="nova-hero"><div><small>INDEPENDENT CREATIVE STUDIO</small><h1>{heroHeadline(store)||<>Ideas with<br/><i>intent.</i></>}</h1><p>{heroSub(store,"Brand, digital and visual work for ambitious businesses.")}</p><Link href={href(slug,"/catalog")} className="nova-link">Explore the work ↗</Link></div><div className="nova-hero-image" style={image(hero)}/></section><section className="nova-grid"><div><small>SELECTED WORK</small><h2>Designed to be remembered.</h2></div><Cards p={p} items={catalogItems} limit={6} className="nova-cards"/></section><section className="nova-quote"><span>“</span><blockquote>Good design should feel inevitable — clear, useful and unmistakably yours.</blockquote></section><Footer p={p} dark/></main></div>
}
function Violet({p}:{p:Props}){
 const {store,slug,catalogItems}=p;
 return <div className="lt-root violet"><div className="violet-top">Free delivery on selected orders · New season now live</div><Header p={p} variant="violet"/><section className="violet-hero" style={image(store.bannerUrl||catalogItems[0]?.image)}><div><small>NEW COLLECTION</small><h1>{heroHeadline(store)||<>Find your<br/><em>next favorite.</em></>}</h1><p>{heroSub(store,"Curated products for every style.")}</p><Link href={href(slug,"/catalog")} className="violet-btn">Shop now</Link></div></section><section className="violet-cats"><h2>Browse categories</h2><div>{p.navCategories.slice(0,6).map(c=><Link href={href(slug,`/category/${c.id}`)} key={c.id}><span>{c.name?.[0]}</span><b>{c.name}</b></Link>)}</div></section><section className="lt-section"><div className="lt-section-head"><div><small>BEST SELLERS</small><h2>Popular right now</h2></div><Link href={href(slug,"/catalog")}>See all →</Link></div><Cards p={p} items={catalogItems} className="violet-cards"/></section><section className="violet-band"><div><small>LIMITED OFFER</small><h2>Make room for something new.</h2><Link href={href(slug,"/catalog")}>Shop the collection →</Link></div></section><Footer p={p} dark/></div>
}
function Premium({p}:{p:Props}){
 const {store,slug,catalogItems}=p;
 return <div className="lt-root premium"><div className="premium-bar">Premium marketplace · Fast delivery · Secure checkout</div><Header p={p} variant="premium"/><div className="premium-layout"><aside><b>Shop departments</b>{p.navCategories.slice(0,10).map(c=><Link href={href(slug,`/category/${c.id}`)} key={c.id}>{c.name}<span>›</span></Link>)}<div className="premium-side-card"><small>FLASH SALE</small><b>Up to 40% off</b><Link href={href(slug,"/catalog")}>Shop deals</Link></div></aside><main><section className="premium-hero"><div><small>SEASONAL COLLECTION</small><h1>{heroHeadline(store)||<>Elevate your<br/>everyday.</>}</h1><p>{heroSub(store,"Premium picks across fashion, home and lifestyle.")}</p><Link href={href(slug,"/catalog")} className="premium-btn">Shop now</Link></div><div style={image(store.bannerUrl||catalogItems[0]?.image)}/></section><div className="premium-rail-head"><h2>Flash sales</h2><span>Ends soon</span></div><Cards p={p} items={catalogItems} limit={4} className="premium-cards"/><div className="premium-rail-head"><h2>Recommended for you</h2><Link href={href(slug,"/catalog")}>View all</Link></div><Cards p={p} items={catalogItems.slice(4)} limit={8} className="premium-cards"/></main></div><Footer p={p}/></div>
}
function HomeVista({p}:{p:Props}){
 const {store,slug,catalogItems}=p;
 return <div className="lt-root homevista"><Header p={p} variant="homevista"/><section className="hv-hero"><div><small>FIND. BUY. LIVE BETTER.</small><h1>{heroHeadline(store)||<>Find your<br/><em>dream home.</em></>}</h1><p>{heroSub(store,"Explore verified properties and find a place you'll love.")}</p><div className="hv-search"><input placeholder="Location, neighborhood or property"/><select><option>Any property type</option><option>Apartment</option><option>House</option></select><Link href={href(slug,"/catalog")}>Search</Link></div></div><div style={image(store.bannerUrl||catalogItems[0]?.image)}/></section><section className="hv-types"><h2>Explore property types</h2><div>{["Apartments","Houses","Villas","Commercial","Land"].map(x=><Link href={href(slug,"/catalog")} key={x}><span>⌂</span><b>{x}</b><small>Verified listings</small></Link>)}</div></section><section className="lt-section"><div className="lt-section-head"><div><small>FEATURED LISTINGS</small><h2>Homes worth seeing</h2></div><Link href={href(slug,"/catalog")}>View all →</Link></div><Cards p={p} items={catalogItems} className="hv-cards"/></section><section className="hv-agent"><div><small>LOCAL EXPERTS</small><h2>Find the right place with confidence.</h2><p>Verified listings, useful details and a simple path from discovery to enquiry.</p><Link href={href(slug,"/search")}>Talk to us →</Link></div><div className="hv-map">PROPERTY MAP</div></section><Footer p={p}/></div>
}
function Rrw({p}:{p:Props}){
 const {store,slug,catalogItems}=p;
 return <div className="lt-root rrw"><Header p={p} variant="rrw"/><section className="rrw-hero" style={image(store.bannerUrl||catalogItems[0]?.image)}><div><small>PREMIUM RENTAL</small><h1>{heroHeadline(store)||<>Drive something<br/><em>worth remembering.</em></>}</h1><p>{heroSub(store,"A stress-free rental experience with simple search and premium vehicles.")}</p><Link href={href(slug,"/catalog")} className="rrw-btn">Browse fleet</Link></div></section><section className="rrw-pills"><span>Airport pickup</span><span>Flexible rental</span><span>Premium support</span><span>Secure booking</span></section><section className="lt-section"><div className="lt-section-head"><div><small>THE FLEET</small><h2>Choose your drive</h2></div><Link href={href(slug,"/catalog")}>View fleet →</Link></div><Cards p={p} items={catalogItems} className="rrw-cards"/></section><section className="rrw-benefits"><div><b>01</b><h3>Simple pickup</h3><p>Choose a convenient location and get on the road quickly.</p></div><div><b>02</b><h3>Premium vehicles</h3><p>Well-presented vehicles ready for business, travel and weekends.</p></div><div><b>03</b><h3>Clear pricing</h3><p>No confusing process — select, book and go.</p></div></section><Footer p={p} dark/></div>
}
function Marketplace({p}:{p:Props}){
 const {store,slug,catalogItems}=p;
 return <div className="lt-root marketplace"><div className="market-top"><b>{store.name}</b><span>Free delivery · Daily deals · Secure payments</span></div><div className="market-search"><Link href={href(slug)} className="lt-brand">{store.name}</Link><input placeholder="Search products, services and categories"/><button>Search</button><Link href={href(slug,"/cart")}>Cart</Link></div><div className="market-layout"><aside><b>Categories</b>{p.navCategories.slice(0,12).map(c=><Link href={href(slug,`/category/${c.id}`)} key={c.id}>{c.name}<span>›</span></Link>)}</aside><main><section className="market-hero"><div><small>EVERYTHING YOU NEED</small><h1>{heroHeadline(store)||<>All in one place.</>}</h1><p>{heroSub(store,"Shop products, discover services and compare the right choice.")}</p><Link href={href(slug,"/catalog")}>Shop now →</Link></div></section><div className="market-services"><span>🚚 Fast delivery</span><span>🛡 Buyer protection</span><span>♧ Verified sellers</span><span>☎ Support</span></div><section className="lt-section"><div className="lt-section-head"><h2>Featured products</h2><Link href={href(slug,"/catalog")}>View all →</Link></div><Cards p={p} items={catalogItems} className="market-cards"/></section><section className="market-promo"><div><small>SPONSORED PARTNERS</small><h2>Discover trusted brands.</h2><p>Quality businesses, useful services and products in one marketplace.</p></div><Link href={href(slug,"/search")}>Explore partners →</Link></section></main></div><Footer p={p} dark/></div>
}
function Arcova({p}:{p:Props}){
 const {store,slug,catalogItems}=p; const hero=store.bannerUrl||catalogItems[0]?.image;
 return <div className="lt-root arcova"><Header p={p} variant="arcova"/><section className="arc-hero"><div><small>ARCHITECTURE / SPACE / FORM</small><h1>{heroHeadline(store)||<>We design spaces<br/><em>with purpose.</em></>}</h1><p>{heroSub(store,"Architecture and built-environment services shaped by context, clarity and craft.")}</p><Link href={href(slug,"/catalog")} className="arc-btn">View projects ↗</Link></div><div style={image(hero)}/></section><section className="arc-intro"><small>OUR APPROACH</small><h2>Less noise.<br/>More intention.</h2><p>From concept to completion, we create environments that feel considered, functional and enduring.</p></section><section className="arc-projects"><div className="lt-section-head"><div><small>SELECTED PROJECTS</small><h2>Recent work</h2></div><Link href={href(slug,"/catalog")}>All projects →</Link></div><Cards p={p} items={catalogItems} className="arc-cards"/></section><section className="arc-quote"><span>“</span><h2>Architecture should make everyday life feel better.</h2><Link href={href(slug,"/search")}>Start a conversation →</Link></section><Footer p={p} dark/></div>
}
function Rivora({p}:{p:Props}){return <div className="lt-root rivora"><Header p={p} variant="rivora"/><section className="riv-hero"><div><small>FRESH EVERY DAY</small><h1>{heroHeadline(p.store)||<>Good food,<br/><em>less friction.</em></>}</h1><p>{heroSub(p.store,"Fresh groceries and everyday essentials delivered to your door.")}</p><Link href={href(p.slug,"/catalog")} className="riv-btn">Shop fresh picks</Link></div><div style={image(p.store.bannerUrl||p.catalogItems[0]?.image)}/></section><section className="riv-cats">{p.navCategories.slice(0,6).map(c=><Link href={href(p.slug,`/category/${c.id}`)} key={c.id}><b>{c.name}</b><span>Fresh picks →</span></Link>)}</section><section className="lt-section"><div className="lt-section-head"><div><small>FRESH PICKS</small><h2>This week's basket</h2></div><Link href={href(p.slug,"/catalog")}>View all →</Link></div><Cards p={p} items={p.catalogItems}/></section><Footer p={p}/></div>}
function JuiceLife({p}:{p:Props}){return <div className="lt-root juicelife"><Header p={p} variant="juicelife"/><section className="juice-hero" style={image(p.store.bannerUrl||p.catalogItems[0]?.image)}><div><small>COLD-PRESSED / NATURAL</small><h1>{heroHeadline(p.store)||<>Drink good.<br/><em>Feel good.</em></>}</h1><p>{heroSub(p.store,"Cold-pressed juices, wellness blends and fresh daily energy.")}</p><Link href={href(p.slug,"/catalog")} className="juice-btn">Shop juices →</Link></div></section><section className="juice-flavors">{["Detox","Energy","Glow","Immunity"].map((x,i)=><Link href={href(p.slug,"/catalog")} key={x}><span>{["🥬","⚡","✨","🍊"][i]}</span><b>{x}</b><small>Fresh blend</small></Link>)}</section><section className="lt-section"><div className="lt-section-head"><div><small>BEST SELLERS</small><h2>Juice bar favorites</h2></div><Link href={href(p.slug,"/catalog")}>View all →</Link></div><Cards p={p} items={p.catalogItems} className="juice-cards"/></section><Footer p={p} dark/></div>}
function Fabtex({p}:{p:Props}){return <div className="lt-root fabtex"><Header p={p} variant="fabtex"/><section className="fab-hero"><div><small>FABRIC / FORM / FASHION</small><h1>{heroHeadline(p.store)||<>Make a statement<br/><em>with what you wear.</em></>}</h1><p>{heroSub(p.store,"Textiles, fashion and pieces made to stand out.")}</p><Link href={href(p.slug,"/catalog")} className="fab-btn">Explore the edit →</Link></div><div style={image(p.store.bannerUrl||p.catalogItems[0]?.image)}/></section><section className="fab-marquee">NEW SEASON · FABTEX · LIMITED EDITS · NEW SEASON · FABTEX · LIMITED EDITS</section><section className="lt-section"><div className="lt-section-head"><div><small>THE EDIT</small><h2>Featured pieces</h2></div><Link href={href(p.slug,"/catalog")}>Shop all →</Link></div><Cards p={p} items={p.catalogItems} className="fab-cards"/></section><section className="fab-editorial"><div><small>CRAFTED WITH INTENT</small><h2>Texture. Colour. Character.</h2><p>Build a wardrobe and a brand presence around pieces that feel unmistakably yours.</p></div><div style={image(p.catalogItems[1]?.image||p.store.bannerUrl)}/></section><Footer p={p}/></div>}

export function LegacyTemplateHome({name,p}:{name:string;p:Props}){
 if(name==="Heenzy Sneaker Co."||name==="Heenzy — Boutique Rose") return <HeenzyStorefront {...p as any} catalogCategories={[]} />;
 if(name==="Fresh & Co.") return <Fresh p={p}/>;
 if(name.startsWith("Nova Studio")) return <Nova p={p}/>;
 if(name.startsWith("Violet")) return <Violet p={p}/>;
 if(name==="Premium Marketplace") return <Premium p={p}/>;
 if(name==="HomeVista") return <HomeVista p={p}/>;
 if(name==="rRW Premium Rental") return <Rrw p={p}/>;
 if(name==="Marketplace Hub") return <Marketplace p={p}/>;
 if(name==="Arcova Architecture") return <Arcova p={p}/>;
 if(name==="Rivora Fresh") return <Rivora p={p}/>;
 if(name==="JuiceLife") return <JuiceLife p={p}/>;
 if(name==="Fabtex") return <Fabtex p={p}/>;
 return null;
}
