import {notFound} from "next/navigation";
import {prisma} from "@/lib/prisma";
import {getTasteHouseContent} from "@/lib/tastehouse-content";
import {saveTasteHouseContent} from "@/lib/actions/tastehouse-content";
import { auth } from "@/lib/auth"; import { redirect } from "next/navigation"; import { assertStorePermission } from "@/lib/access/assert-store-access";

export default async function TasteHouseAdmin({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params; const session=await auth(); if(!session?.user?.id) redirect(`/login?callbackUrl=/store/${slug}/admin/tastehouse`); const access=await assertStorePermission(slug,"settings"); if(!access.success) redirect(`/store/${slug}/admin`); const store=await prisma.store.findUnique({where:{slug},select:{name:true,businessType:true,template:{select:{name:true}}}}); if(!store)notFound();
 const content=await getTasteHouseContent(slug);
 async function save(fd:FormData){"use server"; await saveTasteHouseContent(slug,{heroTitle:String(fd.get('heroTitle')||''),heroAccent:String(fd.get('heroAccent')||''),heroSubtitle:String(fd.get('heroSubtitle')||''),heroImage:String(fd.get('heroImage')||''),firstOfferTitle:String(fd.get('firstOfferTitle')||''),firstOfferText:String(fd.get('firstOfferText')||''),firstOfferImage:String(fd.get('firstOfferImage')||''),secondOfferTitle:String(fd.get('secondOfferTitle')||''),secondOfferText:String(fd.get('secondOfferText')||''),secondOfferImage:String(fd.get('secondOfferImage')||''),supportEmail:String(fd.get('supportEmail')||''),supportPhone:String(fd.get('supportPhone')||'')});}
 return <main className="mx-auto max-w-5xl p-8"><div className="mb-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-orange-600">TasteHouse template controls</p><h1 className="mt-2 text-3xl font-bold text-slate-900">Website content</h1><p className="mt-2 text-slate-500">Control the TasteHouse homepage promotions and customer support content. Products, categories, coupons, orders, reservations and reviews remain controlled by their existing admin modules.</p></div><form action={save} className="space-y-6"><section className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Homepage hero</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><label>Headline<input name="heroTitle" defaultValue={content.heroTitle} className="bn-admin-input"/></label><label>Accent headline<input name="heroAccent" defaultValue={content.heroAccent} className="bn-admin-input"/></label><label className="md:col-span-2">Subtitle<textarea name="heroSubtitle" defaultValue={content.heroSubtitle} className="bn-admin-input"/></label><label className="md:col-span-2">Hero image URL<input name="heroImage" defaultValue={content.heroImage} className="bn-admin-input"/></label></div></section><section className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Promotional cards</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><label>Offer 1 title<input name="firstOfferTitle" defaultValue={content.firstOfferTitle} className="bn-admin-input"/></label><label>Offer 1 text<input name="firstOfferText" defaultValue={content.firstOfferText} className="bn-admin-input"/></label><label>Offer 1 image<input name="firstOfferImage" defaultValue={content.firstOfferImage} className="bn-admin-input"/></label><label>Offer 2 title<input name="secondOfferTitle" defaultValue={content.secondOfferTitle} className="bn-admin-input"/></label><label>Offer 2 text<input name="secondOfferText" defaultValue={content.secondOfferText} className="bn-admin-input"/></label><label>Offer 2 image<input name="secondOfferImage" defaultValue={content.secondOfferImage} className="bn-admin-input"/></label></div></section><section className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Support</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><label>Support email<input name="supportEmail" defaultValue={content.supportEmail} className="bn-admin-input"/></label><label>Support phone<input name="supportPhone" defaultValue={content.supportPhone} className="bn-admin-input"/></label></div></section><button className="rounded-xl bg-orange-600 px-6 py-3 font-bold text-white">Save TasteHouse Changes</button></form></main>
}
