import { notFound } from "next/navigation";
import Link from "next/link";
import { Heart, Users, BedDouble, Maximize2, Trash2 } from "lucide-react";
import { getStoreBranding } from "@/lib/actions/store-branding";
import { listStoreWishlist } from "@/lib/actions/account";
import { getHotelContent } from "@/lib/hotel-content";
import { VelouraAccountHero } from "@/components/storefront/veloura-account-shell";
const money=(v:any,c="NGN")=>`${c==="NGN"?"₦":c+" "}${Number(v||0).toLocaleString()}`;
export default async function Page({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const[store,items,hotel]=await Promise.all([getStoreBranding(slug),listStoreWishlist(slug),getHotelContent(slug)]);if(!store)notFound();const hero=hotel.rooms[0]?.image||null;const rooms=items.filter((i:any)=>i.service);return <div className="veloura-account-content"><VelouraAccountHero title="Saved Rooms" subtitle="Your favourite rooms, saved for later. Find them here anytime and book when you’re ready." image={hero}/><div className="veloura-page-tools"><h2 style={{margin:0,font:"18px Georgia,serif"}}>Saved Rooms ({rooms.length})</h2><div className="veloura-search"><input placeholder="Search your saved rooms..."/><select className="veloura-select"><option>Recently Added</option></select></div></div>{rooms.length?<div className="veloura-room-grid" style={{gridTemplateColumns:"1fr 1fr"}}>{rooms.map((item:any)=>{const r=item.service;const a=(r.attributes||{}) as any;return <article className="veloura-room-card" key={item.id} style={{background:"#fff"}}><div style={{position:"relative"}}><img src={r.images?.[0]||hero||""} alt="" style={{height:155}}/><span style={{position:"absolute",right:12,top:12,width:34,height:34,borderRadius:"50%",background:"#fff",display:"grid",placeItems:"center",color:"#d33"}}><Heart fill="currentColor"/></span></div><div style={{padding:14}}><div style={{display:"flex",justifyContent:"space-between"}}><h3 style={{fontSize:18}}>{r.name}</h3><Trash2 size={17}/></div><p>{r.description||""}</p><div className="veloura-icon-row"><span><Users/>{a.maxGuests||"—"} Guests</span><span><BedDouble/>{a.bedType||"—"}</span><span><Maximize2/>{a.roomSize?`${a.roomSize} m²`:"—"}</span></div><p style={{marginTop:15}}>From <strong>{money(r.price,r.currency)}</strong> / night</p><div className="veloura-room-actions"><Link href={`/store/${slug}/rooms/${r.slug}`}>View Details</Link><Link href={`/store/${slug}/booking`}>Book Now →</Link></div></div></article>})}</div>:<div className="veloura-empty"><Heart style={{margin:"0 auto 10px"}}/>Your saved rooms are empty.<div style={{marginTop:10}}><Link href={`/store/${slug}/rooms`}>Explore Rooms →</Link></div></div>}</div>}
